import React,{useEffect,useRef,useState}from'react';
import type{ResourceItem}from'./resourceCatalog';
import{ResourcePreview}from'./ResourcePreview';
export function ResourceCarousel({items,isArabic,onSelect}:{items:ResourceItem[];isArabic:boolean;onSelect:(item:ResourceItem)=>void}){
 const[active,setActive]=useState(0),start=useRef<number|null>(null),dragged=useRef(false);
 useEffect(()=>setActive(0),[items]);
 useEffect(()=>{if(items.length<2||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const timer=window.setInterval(()=>{if(start.current===null)setActive(v=>(v+1)%items.length)},4600);return()=>clearInterval(timer)},[items.length]);
 if(!items.length)return <p className="py-14 text-center text-sm text-gray-500">{isArabic?'لا توجد نتائج مطابقة.':'No matching results.'}</p>;
 const offsets=items.length===1?[0]:items.length===2?[0,1]:items.length===3?[-1,0,1]:items.length===4?[-1,0,1,2]:[-2,-1,0,1,2];
 return <div className="relative mx-auto h-[270px] max-w-[800px] touch-pan-y select-none overflow-hidden sm:h-[350px]" dir="ltr" onPointerDown={e=>{start.current=e.clientX;dragged.current=false}} onPointerUp={e=>{if(start.current===null)return;const d=e.clientX-start.current;dragged.current=Math.abs(d)>20;if(Math.abs(d)>35)setActive(v=>(v+(d<0?1:-1)+items.length)%items.length);start.current=null}} onPointerCancel={()=>{start.current=null}}>{offsets.map(offset=>{const item=items[(active+offset+items.length)%items.length],distance=Math.abs(offset);return <button type="button" key={item.id} aria-label={isArabic?item.ar:item.en} onClick={()=>{if(dragged.current){dragged.current=false;return}if(offset)setActive(v=>(v+offset+items.length)%items.length);else onSelect(item)}} className="absolute left-1/2 top-1/2 w-[245px] overflow-hidden rounded-3xl border bg-[#111] shadow-2xl transition-[transform,opacity] duration-[1100ms] ease-out sm:w-[330px]" style={{zIndex:10-distance,opacity:distance===2?.25:distance===1?.65:1,borderColor:distance===0?'#D51F2B88':'#ffffff22',transform:`translate3d(calc(-50% + ${offset*112}px),-50%,0) scale(${distance===0?1:distance===1?.78:.61})`}}><ResourcePreview item={item} isArabic={isArabic}/><h3 dir={isArabic?'rtl':'ltr'} className="px-4 py-3 text-start text-sm font-bold text-white">{isArabic?item.ar:item.en}</h3></button>})}</div>;
}
