import React,{useRef,useEffect,useState}from'react';
import type{ResourceItem}from'./resourceCatalog';
import{resourceSvg,svgUrl,gradientCss,textCss}from'./resourceDesign';
import{templateDefaults,templateHtml}from'./templateDesign';
import{brandResources}from'./brandResources';
function TemplateThumbnail({item,isArabic}:{item:ResourceItem;isArabic:boolean}){
 const box=useRef<HTMLDivElement>(null),[width,setWidth]=useState(320);useEffect(()=>{const observer=new ResizeObserver(([entry])=>setWidth(entry.contentRect.width));if(box.current)observer.observe(box.current);return()=>observer.disconnect()},[]);
 const v={...templateDefaults(item.type||'profile-templates',isArabic),name:isArabic?'اسمك هنا':'Your Name',color:item.colors[1]};
 return <div ref={box} className="pointer-events-none relative aspect-[4/3] overflow-hidden bg-[#dedee2]"><iframe tabIndex={-1} aria-hidden="true" title={isArabic?'تصميم القالب':'Template design'} srcDoc={templateHtml(item.type||'profile-templates',item.variant,v,isArabic)} sandbox="" style={{width:800,height:1100,transform:`scale(${width/800})`,transformOrigin:'top left',position:'absolute',left:0,top:0,border:0}}/></div>;
}
export function ResourcePreview({item,isArabic,text,color,playable=false}:{item:ResourceItem;isArabic:boolean;text?:string;color?:string;playable?:boolean}){
 const name=isArabic?item.ar:item.en;
 if(item.kind==='template')return <TemplateThumbnail item={item} isArabic={isArabic}/>;
 if(item.kind==='wallpaper'||item.kind==='avatar')return <img loading="lazy" draggable={false} src={item.preview||item.image} alt={name} className="aspect-[4/3] w-full object-cover"/>;
 if(item.kind==='sizes'){const brand=brandResources.find(x=>x.brand===item.id.split('-')[0]),vertical=(item.height||1)>(item.width||1);return <div className="relative flex aspect-[4/3] flex-col items-center justify-center gap-3 overflow-hidden bg-[#111] p-5"><div className="absolute -right-8 -top-8 h-40 w-40 rounded-full opacity-20 blur-2xl" style={{background:brand?.colors[0]||'#D51F2B'}}/><div className="flex w-full items-center justify-between"><span className="text-xs font-bold text-white">{name.split(' · ')[0]}</span>{brand&&<span className="grid h-10 w-10 place-items-center rounded-xl bg-white"><img src={brand.image} alt="" className="h-6 w-6"/></span>}</div><div className={`relative grid place-items-center rounded-xl border border-[#D51F2B]/40 bg-gradient-to-br from-[#D51F2B]/15 to-[#202028] ${vertical?'h-28 w-20':'h-20 w-40'}`}><span className="text-2xl font-black text-white/25">{item.type==='video'?'▶':'▧'}</span><span className="absolute bottom-2 text-[8px] text-gray-400">{item.width===item.height?'1:1':vertical?(item.width===1080&&item.height===1440?'3:4':'9:16'):'LANDSCAPE'}</span></div><p dir="ltr" className="font-mono text-sm font-bold text-white">{item.width} × {item.height} px</p></div>}
 if(item.kind==='icons')return <div className="flex aspect-[4/3] flex-col items-center justify-center gap-5 bg-[#111]"><span className="grid h-28 w-28 place-items-center rounded-[28px] bg-white shadow-xl"><img src={item.image} alt={name} className="h-16 w-16 object-contain"/></span><p className="text-sm font-bold text-white">{item.en}</p><span className="text-[10px] text-gray-500">SVG · PNG</span></div>;
 if(item.kind==='palette')return <div className="grid aspect-[4/3] grid-cols-4">{item.colors.map(c=><div key={c} style={{background:c}} className="flex items-end justify-center pb-5 text-[10px] text-white [text-shadow:0_1px_3px_black]">{c}</div>)}</div>;
 if(item.kind==='gradient')return <div className="aspect-[4/3]" style={{background:gradientCss(item)}}/>;
 if(item.kind==='font'||item.kind==='text'){
 const styles=Object.fromEntries(textCss(item).split(';').filter(Boolean).map(rule=>{const i=rule.indexOf(':');return[rule.slice(0,i).trim().replace(/-([a-z])/g,(_,c)=>c.toUpperCase()),rule.slice(i+1).trim()]}));
 const latinFont=item.kind==='font'&&item.categoryEn==='English';
 return <div className="relative flex aspect-[4/3] flex-col items-center justify-center gap-3 overflow-hidden bg-[#111] p-5 text-center"><style>{item.font?`@font-face{font-family:${item.family};src:url('${item.font}') format('truetype');font-display:swap}`:"@font-face{font-family:CreatorCairo;src:url('/assets/resource-fonts/cairo.ttf');font-display:swap}@font-face{font-family:CreatorAmiri;src:url('/assets/resource-fonts/amiri.ttf');font-display:swap}@font-face{font-family:CreatorChanga;src:url('/assets/resource-fonts/changa.ttf');font-display:swap}@font-face{font-family:CreatorInter;src:url('/assets/resource-fonts/inter.ttf');font-display:swap}"}</style><span className="absolute left-4 top-3 font-mono text-[9px] text-gray-500">{item.kind==='font'?item.en:String(item.variant+1).padStart(2,'0')+' / TYPE'}</span><span className="break-words text-[32px] leading-tight" style={item.kind==='font'?{fontFamily:item.family,color:'#fff'}:styles}>{text||(latinFont?'Create your story':'اصنع حكايتك')}</span><span dir="ltr" className="text-xl leading-tight" style={item.kind==='font'?{fontFamily:item.family,color:'#bbb'}:styles}>{text?'Aa / أب':'Make it memorable'}</span><span className="absolute bottom-3 text-[9px] text-gray-500">{item.kind==='font'?(latinFont?'LATIN':'ARABIC + LATIN'):'العربية · English'}</span></div>;
 }
 if(item.kind==='prompt')return <div className="relative aspect-[4/3] bg-black">{playable?<video src={item.video} poster={item.preview} controls playsInline preload="metadata" className="h-full w-full object-contain"/>:<><img loading="lazy" draggable={false} src={item.preview} alt={name} className="h-full w-full object-cover"/><span className="absolute inset-0 grid place-items-center"><span className="grid h-12 w-12 place-items-center rounded-full border border-white/30 bg-black/60 text-xl text-white">▶</span></span><span className="absolute bottom-3 right-3 rounded-lg bg-black/70 px-3 py-1 text-[10px] text-white">{isArabic?'معاينة فيديو':'Video preview'}</span></>}</div>;
 return <img draggable={false} loading="lazy" src={svgUrl(resourceSvg(item,color))} alt={name} className="aspect-[4/3] w-full object-cover"/>;
}
