import React from'react';
import type{ResourceItem}from'./resourceCatalog';
import{resourceSvg,svgUrl,gradientCss,textCss}from'./resourceDesign';
const portraits=['people-blue-hour.webp','people-monochrome-street.webp','ember-portrait.webp','people-cafe-thought.webp','people-desert-dusk.webp','people-coffee-kiosk.webp','people-botanical-vector.webp','people-bridge-shadow.webp','people-cloud-room.webp','people-desert-camp.webp','people-miniature-courtyard.webp','people-clay-orchestra.webp'];
export function ResourcePreview({item,isArabic,text,color}:{item:ResourceItem;isArabic:boolean;text?:string;color?:string}){
 const name=isArabic?item.ar:item.en;
 if(item.kind==='palette')return <div className="grid aspect-[4/3] grid-cols-4">{item.colors.map(c=><div key={c} style={{background:c}} className="flex items-end justify-center pb-5 text-[10px] text-white [text-shadow:0_1px_3px_black]">{c}</div>)}</div>;
 if(item.kind==='gradient')return <div className="aspect-[4/3]" style={{background:gradientCss(item)}}/>;
 if(item.kind==='font'||item.kind==='text')return <div className="flex aspect-[4/3] items-center justify-center overflow-hidden p-6 text-center" style={{background:item.colors[0]}}><style>{`@font-face{font-family:ResourceSans;src:url('/assets/resource-fonts/NotoSansArabic.ttf') format('truetype');font-display:swap}@font-face{font-family:ResourceNaskh;src:url('/assets/resource-fonts/NotoNaskhArabic.ttf') format('truetype');font-display:swap}`}</style><span style={item.kind==='font'?{fontFamily:item.family,color:item.colors[2],fontSize:38}:undefined} className="break-words text-3xl font-black"><span style={item.kind==='text'?Object.fromEntries(textCss(item).split(';').filter(Boolean).map(rule=>{const i=rule.indexOf(':');const key=rule.slice(0,i).trim().replace(/-([a-z])/g,(_,c)=>c.toUpperCase());return[key==='WebkitBackgroundClip'?'WebkitBackgroundClip':key,rule.slice(i+1).trim()]})):undefined}>{text||(isArabic?'الحكاية تبدأ منك':'Your story starts here')}</span></span></div>;
 if(item.kind==='prompt')return <div className="relative aspect-[4/3]"><img loading="lazy" draggable={false} src={`/assets/prompts/${portraits[item.variant%portraits.length]}`} alt="" className="h-full w-full object-cover"/><div className="absolute inset-0 flex items-end bg-gradient-to-t from-black/80 to-transparent p-4"><span className="text-[10px] font-bold text-white">{isArabic?'صورة مرجعية توضيحية · برومبت فيديو':'Illustrative reference · Video prompt'}</span></div></div>;
 return <img draggable={false} loading="lazy" src={svgUrl(resourceSvg(item,color))} alt={name} className="aspect-[4/3] w-full object-cover"/>;
}
