import{brandResources}from'./brandResources';
import{fontResources}from'./fontResources';
export type ResourceKind='sizes'|'template'|'prompt'|'wallpaper'|'icons'|'font'|'avatar'|'palette'|'gradient'|'text';
export type ResourceItem={id:string;ar:string;en:string;category:string;categoryEn:string;kind:ResourceKind;colors:string[];variant:number;prompt?:string;promptEn?:string;font?:string;license?:string;family?:string;source?:string;width?:number;height?:number;type?:string;image?:string;preview?:string;video?:string;brand?:string};
export type ResourceCollection={id:string;ar:string;en:string;description:string;descriptionEn:string;items:ResourceItem[]};
const colors=[['#101014','#D51F2B','#F5F5F5','#A1A1AA'],['#102E31','#16A085','#F3E9D2','#79B4A9'],['#172033','#4271DE','#E3EDFF','#8090B8'],['#321B28','#C75C84','#F8D8E5','#8D546E'],['#292116','#BF9655','#F3E8D1','#807054'],['#251E38','#956CE0','#ECE3FF','#66537F']];
function item(id:string,ar:string,en:string,kind:ResourceKind,variant:number,extra:Partial<ResourceItem>={}):ResourceItem{return{id,ar,en,kind,variant,colors:colors[variant%colors.length],category:ar,categoryEn:en,...extra};}
const social=[
 item('instagram-square','إنستقرام · صورة مربعة','Instagram · Square image','sizes',0,{category:'إنستقرام',categoryEn:'Instagram',width:1080,height:1080,source:'https://help.instagram.com/1631821640426723/'}),
 item('instagram-portrait','إنستقرام · صورة طولية','Instagram · Portrait image','sizes',1,{category:'إنستقرام',categoryEn:'Instagram',width:1080,height:1440,source:'https://help.instagram.com/1631821640426723/'}),
 item('instagram-reel','إنستقرام · ريلز','Instagram · Reels','sizes',2,{category:'إنستقرام',categoryEn:'Instagram',width:1080,height:1920,source:'https://help.instagram.com/1038071743007909/',type:'video'}),
 item('tiktok-video','تيك توك · فيديو عمودي','TikTok · Vertical video','sizes',3,{category:'تيك توك',categoryEn:'TikTok',width:1080,height:1920,source:'https://ads.tiktok.com/business/en/guides/video-advertising-guide',type:'video'}),
 item('snapchat-image','سناب شات · صورة عمودية','Snapchat · Vertical image','sizes',4,{category:'سناب شات',categoryEn:'Snapchat',width:1080,height:1920,source:'https://forbusiness.snapchat.com/advertising/ad-formats'}),
 item('snapchat-video','سناب شات · فيديو عمودي','Snapchat · Vertical video','sizes',5,{category:'سناب شات',categoryEn:'Snapchat',width:1080,height:1920,source:'https://forbusiness.snapchat.com/advertising/ad-formats',type:'video'}),
 item('youtube-banner','يوتيوب · بنر القناة','YouTube · Channel banner','sizes',0,{category:'يوتيوب',categoryEn:'YouTube',width:2560,height:1440,source:'https://support.google.com/youtube/answer/10456525'}),
 item('youtube-thumbnail','يوتيوب · صورة مصغرة','YouTube · Thumbnail','sizes',1,{category:'يوتيوب',categoryEn:'YouTube',width:3840,height:2160,source:'https://support.google.com/youtube/answer/72431'}),
 item('youtube-video','يوتيوب · فيديو أفقي','YouTube · Landscape video','sizes',2,{category:'يوتيوب',categoryEn:'YouTube',width:1920,height:1080,source:'https://support.google.com/youtube/answer/6375112',type:'video'}),
 item('x-header','إكس · بنر الحساب','X · Header','sizes',3,{category:'إكس',categoryEn:'X',width:1500,height:500,source:'https://help.x.com/en/managing-your-account/common-issues-when-uploading-profile-photo'}),
 item('x-avatar','إكس · صورة الحساب','X · Profile image','sizes',4,{category:'إكس',categoryEn:'X',width:400,height:400,source:'https://help.x.com/en/managing-your-account/common-issues-when-uploading-profile-photo'}),
];
const promptScenes=[
 ['بورتريه متحرك','Living Portrait','شخص من الصورة المرجعية يلتفت ببطء نحو الكاميرا، إضاءة جانبية دافئة وخلفية داكنة، حركة كاميرا اقتراب بطيء، لقطة واحدة متصلة.','The person in the reference image slowly turns toward the camera, warm side lighting, dark background, slow camera push-in, one continuous shot.'],
 ['خطوة في المطر','Walk in the Rain','الشخص يمشي خطوة واحدة في شارع ليلي تحت المطر الخفيف، انعكاسات أضواء حمراء على الأرض، كاميرا تتبع أمامية على مستوى العين.','The person takes one step on a night street in light rain, red reflections on the pavement, eye-level frontal tracking shot.'],
 ['لقاء الميكروفون','At the Microphone','الشخص يستعد للكلام أمام ميكروفون في استوديو داكن، حركة يد طبيعية وتنفس هادئ، اقتراب كاميرا خفيف، إضاءة عملية ناعمة.','The person prepares to speak into a microphone in a dark studio, natural hand motion and calm breathing, gentle camera push-in, soft practical lighting.'],
 ['نور النافذة','Window Light','الشخص جالس قرب نافذة، الستارة تتحرك بخفة ويمر الضوء على الوجه تدريجيًا، الكاميرا ثابتة، مشهد هادئ بتفاصيل بشرة طبيعية.','The person sits by a window, the curtain gently moves and light slowly crosses the face, locked camera, calm scene with natural skin texture.'],
 ['مشي الصحراء','Desert Walk','الشخص يمشي على كثيب رملي عند الغروب، الرياح تحرك الملابس فقط، لقطة واسعة بحركة جانبية بطيئة، ألوان رملية دافئة.','The person walks on a dune at sunset, wind moves only the clothing, wide shot with a slow lateral camera move, warm sand colors.'],
 ['جلسة القهوة','Coffee Moment','الشخص يرفع كوب قهوة نحو الطاولة وينظر إليه، بخار خفيف وإضاءة مقهى دافئة، لقطة متوسطة، حركة يد دقيقة بلا أصابع إضافية.','The person lifts a coffee cup over a table and looks at it, subtle steam and warm café lighting, medium shot, accurate hand movement without extra fingers.'],
 ['تصوير خلف الكواليس','Behind the Camera','الشخص يرفع كاميرا فوتوغرافية نحو العين، إضاءة استوديو ناعمة، لقطة جانبية، حركة كاميرا قوس صغير بلا تغيير للوجه.','The person raises a camera to eye level, soft studio lighting, side view, small camera arc without altering the face.'],
 ['بداية المسرح','Before the Stage','الشخص يقف خلف ستارة مسرح ثم يلتفت نحو الضوء، بقعة ضوء علوية وملمس ستارة واضح، لقطة متصلة بحركة بطيئة.','The person stands behind a stage curtain then turns toward the light, overhead spotlight and visible curtain texture, continuous slow-moving shot.'],
 ['نسيم الساحل','Coastal Breeze','الشخص يقف قرب البحر عند الشروق، نسيم خفيف وأمواج خلفه، كاميرا ثابتة وعمق مجال ناعم، بدون مبالغة في حركة الوجه.','The person stands by the sea at sunrise, light breeze and waves behind them, locked camera and soft depth of field, restrained facial motion.'],
 ['حركة المدينة','City Motion','الشخص ثابت وسط ممر حضري والناس بالخلفية يتحركون بتمويه خفيف، ضوء مسائي، عدسة 50mm، الكاميرا تتقدم ببطء.','The person stands still in an urban walkway while background pedestrians move with gentle blur, evening light, 50mm lens, slow camera approach.'],
 ['كاتب الأفكار','Writing Ideas','الشخص يكتب في دفتر ثم يرفع عينيه نحو الكاميرا، مكتب بسيط وإضاءة نهارية، لقطة متوسطة، الحفاظ على شكل اليد والوجه.','The person writes in a notebook then looks toward the camera, simple desk and daylight, medium shot, preserve hand and facial anatomy.'],
 ['إضاءة حمراء','Red Light Shift','الشخص ينظر إلى الكاميرا بينما يمر ضوء أحمر ناعم عبر الخلفية، إضاءة الوجه ثابتة، لقطة بورتريه قريبة وحركة كاميرا بسيطة.','The person looks at the camera as soft red light moves across the background, face lighting remains steady, close portrait with subtle camera motion.'],
];

const natureScenes=[['mountains','قمم الجبال','Mountain Peaks','جبال','Mountains'],['forest','عمق الغابة','Deep Forest','طبيعة','Nature'],['coast','الساحل','Coast','بحر','Sea'],['lake','انعكاس البحيرة','Lake Reflection','طبيعة','Nature'],['desert','رمال ذهبية','Golden Sands','صحراء','Desert'],['waterfall','شلال','Waterfall','طبيعة','Nature'],['meadow','أزهار الربيع','Spring Blossom','طبيعة','Nature'],['snow','ثلوج','Snow','جبال','Mountains'],['ocean','موج المحيط','Ocean Waves','بحر','Sea'],['sunset','وقت الغروب','Sunset','سماء','Sky'],['pine','غابة الصنوبر','Pine Forest','طبيعة','Nature'],['valley','الوادي','Valley','طبيعة','Nature']];
const profileScenes=[["غروب هادئ","Quiet Sunset"],["ظل المساء","Evening Silhouette"],["سماء داكنة","Dark Sky"],["نظرة الأفق","Horizon Gaze"],["آخر الضوء","Last Light"],["هودي أبيض","White Hoodie"],["تحت السماء","Under the Sky"],["نظرة للشمس","Toward the Sun"],["زاوية جانبية","Side Angle"],["لحظة تأمل","Quiet Reflection"],["ساعة ذهبية","Golden Hour"],["على الساحل","By the Coast"]];

const ipadScenes=[['alpine','قمم الألب','Alpine Peaks','جبال','Mountains'],['mist','غابة الضباب','Misty Forest','طبيعة','Nature'],['island','جزيرة هادئة','Quiet Island','بحر','Sea'],['water','صفاء الماء','Clear Water','طبيعة','Nature'],['dunes','خطوط الرمال','Dune Lines','صحراء','Desert'],['aurora','الشفق القطبي','Northern Lights','سماء','Sky'],['flowers','تفتح الزهور','Blossom','طبيعة','Nature'],['glacier','ليلة جبلية','Mountain Night','جبال','Mountains'],['shore','شاطئ استوائي','Tropical Beach','بحر','Sea'],['clouds','أفق مفتوح','Open Horizon','سماء','Sky'],['green','أخضر عميق','Deep Green','طبيعة','Nature'],['river','شلال شمالي','Northern Falls','طبيعة','Nature']];
export const extraResources:ResourceCollection[]=[
 {id:'social-sizes',ar:'مقاسات السوشال',en:'Social Media Sizes',description:'اختر المنصة ونوع المحتوى، وانسخ المقاس أو نزّل مساحة تصميم جاهزة.',descriptionEn:'Choose a platform and format, copy its dimensions or download a blank canvas.',items:social},
 {id:'video-prompts',ar:'برومبتات فيديو',en:'Video Prompts',description:'أفكار حركة وكاميرا لتحريك صورة شخص مرجعية. انسخ النص وعدّله حسب أداتك.',descriptionEn:'Motion and camera prompts for a reference portrait. Copy and adapt to your video tool.',items:promptScenes.map(([ar,en,prompt,promptEn],i)=>item(`video-prompt-${i}`,ar,en,'prompt',i,{category:'صورة إلى فيديو',categoryEn:'Image to video',video:`/assets/creator-video/${i}.mp4`,preview:`/assets/creator-video/${i}.webp`,prompt:`استخدم الصورة المرفقة مرجعًا للشخص وحافظ على هويته وملامح وجهه ونسب جسمه. ${prompt} مدة مقترحة 5 ثوانٍ، نسبة 9:16، حركة واقعية ومتسقة، بدون نص أو شعارات أو تشوهات أو تغيير الهوية.`,promptEn:`Use the attached image as the person's reference and preserve their identity, facial features and body proportions. ${promptEn} Suggested duration: 5 seconds, 9:16 aspect ratio, realistic consistent motion, no text, logos, distortions or identity changes.`}))},
 ...([['desktop-wallpapers','خلفيات كمبيوتر','Desktop Wallpapers',3840,2160],['ipad-wallpapers','خلفيات ايباد','iPad Wallpapers',2732,2048]]as const).map(([id,ar,en,width,height])=>({id,ar,en,description:'صور طبيعة عالية الدقة من جبال وغابات وبحار وصحارى، جاهزة للتنزيل.',descriptionEn:'High-resolution mountains, forests, oceans and deserts ready to download.',items:(id==='ipad-wallpapers'?ipadScenes:natureScenes).map(([slug,name,nameEn,category,categoryEn],i)=>item(`${id}-${i}`,name,nameEn,'wallpaper',i,{width,height,image:`/assets/${id==='ipad-wallpapers'?'ipad-nature':'creator-nature'}/${slug}.jpg`,preview:`/assets/${id==='ipad-wallpapers'?'ipad-nature':'creator-nature'}/${slug}-preview.webp`,category,categoryEn}))})),
 {id:'app-icons',ar:'ايقونات تطبيقات',en:'App Icons',description:'شعارات التطبيقات المعروفة بصيغ SVG وPNG، بأشكالها الأصلية.',descriptionEn:'Recognizable app logos in their original shapes, as SVG and PNG.',items:brandResources},
 {id:'font-packs',ar:'حزم خطوط',en:'Font Packs',description:'18 خطًا عربيًا وإنجليزيًا بأنماط هندسية ونسخ وعناوين وكتابة تحريرية، مع ملفات الخطوط ورخصها.',descriptionEn:'18 Arabic and Latin fonts: geometric, Naskh, display and editorial families, with original licenses.',items:fontResources},
 {id:'profile-pictures',ar:'صور بروفايل',en:'Profile Pictures',description:'لقطات عفوية وظلال أشخاص مع السماء والغروب، جاهزة للتنزيل.',descriptionEn:'Candid portraits and silhouettes against the sky and sunset, ready to download.',items:profileScenes.map(([name,nameEn],i)=>item(`avatar-mood-${i}`,name,nameEn,'avatar',i,{width:1024,height:1024,image:`/assets/profile-moods/${i}.webp`,preview:`/assets/profile-moods/${i}.webp`,category:i<5||i>9?'ظلال وغروب':'لقطات عفوية',categoryEn:i<5||i>9?'Sunset silhouettes':'Candid portraits'}))},
 {id:'color-palettes',ar:'لوحات ألوان',en:'Color Palettes',description:'انسخ أكواد الألوان أو نزّلها كمتغيرات CSS جاهزة.',descriptionEn:'Copy color codes or download ready-to-use CSS variables.',items:['أحمر تحريري','ساحل','رقمي','وردي','رملي','بنفسجي'].map((name,i)=>item(`palette-${i}`,name,['Editorial Red','Coastal','Digital','Rose','Sand','Violet'][i],'palette',i,{category:'4 ألوان',categoryEn:'4 colors'}))},
 {id:'gradients',ar:'تدرجات لونية',en:'Color Gradients',description:'تدرجات قابلة لنسخ CSS والتنزيل كصورة أو ملف SVG.',descriptionEn:'Copy gradient CSS or download a PNG or SVG image.',items:['وهج أحمر','ساحل أخضر','صعود أزرق','غروب وردي','دفء ذهبي','ضوء بنفسجي'].map((name,i)=>item(`gradient-${i}`,name,['Red Glow','Green Coast','Blue Rise','Pink Sunset','Golden Warmth','Violet Light'][i],'gradient',i,{width:1920,height:1080,category:i%2?'دائري':'خطي',categoryEn:i%2?'Radial':'Linear'}))},
];
