import {escapeMarkup}from'./resourceDesign';
export type TemplateValues={name:string;title:string;email:string;bio:string;details:string;extra:string;color:string};
export function templateDefaults(type:string,ar:boolean):TemplateValues{
 const t=(a:string,e:string)=>ar?a:e;
 return{name:t('اسمك هنا','Your name'),title:t('مجالك أو مسماك','Your role or niche'),email:'name@example.com',bio:t('اكتب نبذة قصيرة عنك وخبرتك وما تقدمه.','Write a short introduction about your expertise and what you offer.'),details:type==='invoice-templates'?t('اسم الخدمة | 1 | 100\nخدمة إضافية | 1 | 50','Service name | 1 | 100\nExtra service | 1 | 50'):type==='media-kit-templates'?t('عدد المتابعين: أدخل بياناتك\nالمشاهدات: أدخل بياناتك\nنسبة التفاعل: أدخل بياناتك\nالخدمات: أدخل خدماتك','Followers: enter your data\nViews: enter your data\nEngagement: enter your data\nServices: enter your services'):type==='cv-templates'?t('الخبرة\nاكتب وظيفتك ومهامك وتاريخها\nالتعليم\nاكتب مؤهلك وتاريخ التخرج\nالمهارات\nاكتب مهاراتك','Experience\nEnter your role, duties and dates\nEducation\nEnter your qualification and graduation date\nSkills\nEnter your skills'):type==='portfolio-templates'?t('اسم المشروع الأول\nوصف المشروع ودورك فيه\nاسم المشروع الثاني\nوصف المشروع ودورك فيه','First project name\nProject description and your role\nSecond project name\nProject description and your role'):t('حساب التواصل الأول\nحساب التواصل الثاني\nخدمة أو مهارة تقدمها','First social account\nSecond social account\nA service or skill you offer'),extra:type==='invoice-templates'?t('اسم العميل\nرقم الفاتورة\nتاريخ الفاتورة','Client name\nInvoice number\nInvoice date'):t('أضف معلومات إضافية أو روابط التواصل.','Add extra information or contact links.'),color:'#D51F2B'};
}
export function templateHtml(type:string,variant:number,v:TemplateValues,ar:boolean){
 const esc=escapeMarkup,t=(a:string,e:string)=>ar?a:e,color=/^#[a-f0-9]{6}$/i.test(v.color)?v.color:'#D51F2B',layout=variant%3;
 const heading=type==='cv-templates'?t('السيرة الذاتية','Curriculum Vitae'):type==='portfolio-templates'?t('أعمال مختارة','Selected Work'):type==='media-kit-templates'?t('ملف التعاون','Media Kit'):type==='invoice-templates'?t('فاتورة','Invoice'):t('الملف الشخصي','Profile');
 const edit=(value:string,tag='p',cls='')=>`<${tag} class="${cls}" contenteditable="true">${esc(value)}</${tag}>`;
 const lines=v.details.split('\n').filter(Boolean);
 const intro=`<span class="monogram">${esc(v.name.trim().slice(0,1))}</span><p class="eyebrow">${heading}</p>${edit(v.name,'h1')}${edit(v.title,'p','role')}${edit(v.email,'p','contact')}`;
 const bio=edit(v.bio,'p','bio'),extra=edit(v.extra,'p','extra');
 const numbered=lines.map((line,i)=>`<div class="row"><span class="index">${String(i+1).padStart(2,'0')}</span>${edit(line)}</div>`).join('');
 let body='';
 if(type==='profile-templates'){
  const links=lines.map((line,i)=>`<div class="profile-link"><span class="link-icon">${['↗','◎','✉','◇'][i%4]}</span>${edit(line)}<span>↗</span></div>`).join('');
  body=layout===0?`<div class="profile-cover"><div class="cover-orbit"></div><p>PERSONAL / PROFILE</p></div><header class="profile-center">${intro}</header><section class="profile-body">${bio}${links}${extra}</section>`:layout===1?`<header class="profile-editorial">${intro}${bio}</header><section class="profile-body"><h2>${t('تواصل معي','Connect with me')}</h2>${links}${extra}</section>`:`<div class="profile-split"><header>${intro}${bio}</header><section><h2>${t('روابطي وخدماتي','Links & services')}</h2>${links}${extra}</section></div>`;
 }else if(type==='cv-templates'){
  const timeline=lines.map((line,i)=>`<div class="timeline"><span class="timeline-dot"></span><small>${String(i+1).padStart(2,'0')}</small>${edit(line,i%2===0?'h3':'p')}</div>`).join('');
  body=layout===0?`<div class="cv-sidebar"><aside>${intro}<h2>${t('التواصل','Contact')}</h2>${extra}</aside><section><h2>${t('نبذة مهنية','Professional profile')}</h2>${bio}<h2>${t('الخبرات والمؤهلات','Experience & education')}</h2>${timeline}</section></div>`:layout===1?`<header class="cv-editorial">${intro}</header><div class="cv-columns"><section><h2>${t('الخبرات','Experience')}</h2>${timeline}</section><aside><h2>${t('نبذة','Profile')}</h2>${bio}<h2>${t('معلومات إضافية','Additional details')}</h2>${extra}</aside></div>`:`<header class="cv-compact">${intro}</header><section class="content">${bio}<h2>${t('المسار المهني','Career timeline')}</h2>${timeline}<footer>${extra}</footer></section>`;
 }else if(type==='portfolio-templates'){
  const projects=lines.filter((_,i)=>i%2===0).map((line,i)=>`<article class="project"><div class="project-art art-${i%3}"><span>${String(i+1).padStart(2,'0')}</span><i></i></div><div>${edit(line,'h3')}${edit(lines[i*2+1]||t('وصف المشروع ودورك','Project description and your role'))}</div></article>`).join('');
  body=`<header class="portfolio-hero hero-${layout}">${intro}<span class="folio-word">FOLIO</span>${bio}</header><section class="content"><div class="section-label"><h2>${heading}</h2><span>01 — ${String(Math.ceil(lines.length/2)).padStart(2,'0')}</span></div><div class="projects projects-${layout}">${projects}</div><footer>${extra}</footer></section>`;
 }else if(type==='media-kit-templates'){
  const stats=lines.map((line,i)=>{const parts=line.split(':');return`<div class="stat"><small>${String(i+1).padStart(2,'0')}</small>${edit(parts[0],'h3')}${edit(parts.slice(1).join(':')||t('أدخل بياناتك','Enter your data'),'p','stat-value')}</div>`}).join('');
  body=`<header class="media-hero media-${layout}">${intro}<div class="media-mark">M<span>+</span></div></header><section class="content"><h2>${t('عن صانع المحتوى','About the creator')}</h2>${bio}<h2>${t('الجمهور وأرقامك','Audience & metrics')}</h2><div class="stats stats-${layout}">${stats}</div><div class="collab"><h2>${t('التعاون والتواصل','Collaborations & contact')}</h2>${extra}</div></section>`;
 }else{
  const rows=lines.map(line=>{const[name,q,p]=line.split('|');const quantity=Math.max(0,Number(q)||0),price=Math.max(0,Number(p)||0);return{name:name.trim(),quantity,price,total:quantity*price}});
  const total=rows.reduce((sum,row)=>sum+row.total,0).toFixed(2);
  body=`<header class="invoice-head invoice-${layout}"><div>${intro}</div><div class="invoice-label"><span>${heading}</span><p>INVOICE</p></div></header><section class="content"><div class="invoice-meta"><div><h2>${t('معلومات العميل والفاتورة','Client & invoice details')}</h2>${extra}</div><div>${bio}</div></div><table><thead><tr><th>#</th><th>${t('الخدمة','Service')}</th><th>${t('الكمية','Qty')}</th><th>${t('السعر','Price')}</th><th>${t('المجموع','Total')}</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${String(i+1).padStart(2,'0')}</td><td>${esc(r.name)}</td><td>${r.quantity}</td><td>${r.price.toFixed(2)}</td><td>${r.total.toFixed(2)}</td></tr>`).join('')}</tbody></table><div class="invoice-bottom"><p>${t('شكرًا لتعاملك معنا','Thank you for your business')}</p><div class="total">${t('الإجمالي','Total')}<strong>${total} SAR</strong></div></div></section>`;
 }
 return`<!doctype html><html lang="${ar?'ar':'en'}" dir="${ar?'rtl':'ltr'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(v.name)} — ${heading}</title><style>
 *{box-sizing:border-box}body{margin:0;background:#e9e9ec;color:#202126;font-family:Arial,sans-serif;line-height:1.7;--accent:${color}}.sheet{width:800px;max-width:100%;min-height:1050px;margin:20px auto;background:#fff;overflow:hidden;box-shadow:0 12px 60px #0001}p{margin:8px 0;overflow-wrap:anywhere}h1{font-size:42px;line-height:1.2;letter-spacing:-1px;margin:15px 0}h2{font-size:17px;margin:22px 0 15px;padding-bottom:10px;border-bottom:1px solid #ddd}h3{font-size:16px;margin:10px 0}.eyebrow{font-size:10px;letter-spacing:3px;text-transform:uppercase;color:var(--accent);font-weight:bold}.role{font-size:17px}.contact{font-size:12px;direction:ltr}.bio,.extra{white-space:pre-line;font-size:14px}.extra{font-size:12px}.content{padding:36px 44px}.monogram{display:inline-grid;width:60px;height:60px;place-items:center;background:var(--accent);color:#fff;font-size:30px;font-weight:bold;border-radius:18px}.row{display:flex;gap:18px;border-bottom:1px solid #eee;padding:12px 0}.index{color:var(--accent)}footer{margin-top:30px;padding-top:20px;border-top:1px solid #ddd}
 .profile-cover{height:230px;background:#161719;position:relative;overflow:hidden;color:#fff;padding:30px}.profile-cover p{letter-spacing:6px;font-size:12px}.cover-orbit{position:absolute;width:350px;height:350px;border:70px solid var(--accent);border-radius:50%;top:60px;inset-inline-end:-30px}.profile-center{text-align:center;margin-top:-42px;position:relative}.profile-center .monogram{width:84px;height:84px;border:6px solid white;border-radius:50%}.profile-body{padding:25px 75px}.profile-link{display:flex;align-items:center;gap:15px;margin:12px 0;padding:15px 20px;border:1px solid #e0e0e0;border-radius:14px}.profile-link p{flex:1;font-size:14px}.link-icon{color:var(--accent);font-size:24px}.profile-editorial{padding:65px 75px 30px;border-top:12px solid var(--accent)}.profile-editorial h1{font-size:62px;max-width:600px}.profile-split{display:grid;grid-template-columns:45% 55%;min-height:1050px}.profile-split header{padding:65px 38px;background:#17181b;color:white}.profile-split section{padding:100px 35px}.profile-split .bio{margin-top:40px}
 .cv-sidebar{display:grid;grid-template-columns:31% 69%;min-height:1050px}.cv-sidebar aside{padding:45px 26px;background:#182128;color:white}.cv-sidebar aside h1{font-size:30px}.cv-sidebar section{padding:40px}.timeline{position:relative;border-inline-start:2px solid #ddd;padding:8px 20px 18px}.timeline-dot{position:absolute;inset-inline-start:-6px;top:18px;width:10px;height:10px;border-radius:50%;background:var(--accent)}.timeline small{color:var(--accent)}.cv-editorial{margin:45px 44px 0;border-bottom:4px solid var(--accent);padding-bottom:30px}.cv-editorial .monogram{float:${ar?'left':'right'}}.cv-columns{display:grid;grid-template-columns:64% 36%;padding:20px 44px;gap:28px}.cv-columns aside{background:#f4f4f4;padding:20px}.cv-compact{padding:45px;background:var(--accent);color:white}.cv-compact .eyebrow{color:white}.cv-compact .monogram{background:white;color:var(--accent);float:${ar?'left':'right'}}
 .portfolio-hero{padding:45px;position:relative;background:#18191e;color:#fff;overflow:hidden}.portfolio-hero .bio{max-width:440px;position:relative}.folio-word{display:block;font-size:108px;line-height:1;font-weight:900;letter-spacing:-7px;color:var(--accent);margin:35px 0}.hero-1{background:#f7f4ed;color:#222}.hero-1 .folio-word{font-family:Georgia,serif;font-weight:400;font-style:italic}.hero-2{background:var(--accent)}.hero-2 .eyebrow,.hero-2 .folio-word{color:#fff}.section-label{display:flex;align-items:center;justify-content:space-between}.section-label span{font-size:11px}.projects{display:grid;gap:24px}.projects-0{grid-template-columns:1fr 1fr}.projects-1 .project{display:grid;grid-template-columns:50% 50%;gap:24px;align-items:center}.projects-2{grid-template-columns:1fr 1fr}.project-art{height:200px;position:relative;overflow:hidden;background:#e6e3da}.project-art span{position:absolute;top:16px;inset-inline-start:16px;font-size:12px}.project-art i{position:absolute;width:130px;height:130px;background:var(--accent);transform:rotate(-25deg);top:50px;left:35%}.art-1{background:#24242a}.art-1 i{border-radius:50%;background:transparent;border:25px solid var(--accent)}.art-2 i{transform:rotate(45deg);border-radius:15px}.projects-2 .project-art{height:280px}.project p{font-size:12px}
 .media-hero{padding:45px;background:#1b1c20;color:white;position:relative;min-height:300px}.media-hero h1{max-width:470px}.media-mark{position:absolute;inset-inline-end:35px;bottom:15px;font-size:130px;font-weight:900;color:var(--accent);line-height:1}.media-mark span{font-size:60px}.media-1{background:#f3eee5;color:#222;border-top:15px solid var(--accent)}.media-2{background:var(--accent)}.media-2 .media-mark,.media-2 .eyebrow{color:#fff}.stats{display:grid;grid-template-columns:1fr 1fr;gap:16px}.stat{padding:24px;background:#f5f5f5;border-top:4px solid var(--accent)}.stat small{font-size:11px;color:var(--accent)}.stat-value{font-size:20px;font-weight:bold}.stats-1 .stat{border:1px solid #ddd;border-radius:50px;background:white}.stats-2{grid-template-columns:1fr}.stats-2 .stat{display:flex;align-items:center;gap:25px}.stats-2 .stat p{margin-inline-start:auto}.collab{margin-top:32px;padding:20px 30px;background:#f5f5f5}
 .invoice-head{display:flex;justify-content:space-between;padding:45px;border-top:12px solid var(--accent)}.invoice-head h1{font-size:28px}.invoice-label{text-align:end}.invoice-label span{font-size:44px;font-weight:900;color:var(--accent)}.invoice-label p{letter-spacing:5px;font-size:12px}.invoice-1{background:#192128;color:white;border:0}.invoice-2{border-top:0;border-bottom:2px solid var(--accent);background:#f8f7f3}.invoice-2 .monogram{border-radius:0}.invoice-meta{display:grid;grid-template-columns:1fr 1fr;gap:30px;margin-bottom:30px}table{width:100%;border-collapse:collapse;font-size:13px}td,th{text-align:start;padding:17px 9px;border-bottom:1px solid #ddd}th{background:var(--accent);color:white}tbody tr:nth-child(even){background:#f7f7f7}.invoice-bottom{display:flex;align-items:center;justify-content:space-between;margin-top:35px}.invoice-bottom p{font-size:12px}.total{padding:22px 30px;background:#f4f4f4;font-size:12px}.total strong{display:block;font-size:25px;color:var(--accent)}
 @page{size:A4;margin:10mm}@media print{body{background:white}.sheet{margin:0;box-shadow:none;min-height:0;width:100%;print-color-adjust:exact;-webkit-print-color-adjust:exact}.project,.stat,.timeline,table{break-inside:avoid}}@media(max-width:550px){.sheet{margin:0}h1{font-size:30px}.content{padding:25px}.profile-body{padding:25px}.profile-split,.cv-sidebar,.cv-columns{grid-template-columns:1fr}.profile-split section{padding:25px}.cv-columns{padding:25px}.folio-word{font-size:65px}.projects-1 .project{grid-template-columns:1fr}.media-mark{font-size:60px}.invoice-head{padding:25px}.invoice-label span{font-size:26px}.invoice-meta{grid-template-columns:1fr}}
 </style></head><body><main class="sheet template-${type} layout-${layout}">${body}</main></body></html>`;
}
