import {escapeMarkup}from'./resourceDesign';
export type TemplateValues={name:string;title:string;email:string;bio:string;details:string;extra:string;color:string};
export function templateDefaults(type:string,ar:boolean):TemplateValues{
 const t=(a:string,e:string)=>ar?a:e;
 return{name:t('اسمك هنا','Your name'),title:t('مجالك أو مسماك','Your role or niche'),email:'name@example.com',bio:t('اكتب نبذة قصيرة عنك وخبرتك وما تقدمه.','Write a short introduction about your expertise and what you offer.'),details:type==='invoice-templates'?t('اسم الخدمة | 1 | 100\nخدمة إضافية | 1 | 50','Service name | 1 | 100\nExtra service | 1 | 50'):type==='media-kit-templates'?t('عدد المتابعين: أدخل بياناتك\nالمشاهدات: أدخل بياناتك\nنسبة التفاعل: أدخل بياناتك\nالخدمات: أدخل خدماتك','Followers: enter your data\nViews: enter your data\nEngagement: enter your data\nServices: enter your services'):type==='cv-templates'?t('الخبرة\nاكتب وظيفتك ومهامك وتاريخها\nالتعليم\nاكتب مؤهلك وتاريخ التخرج\nالمهارات\nاكتب مهاراتك','Experience\nEnter your role, duties and dates\nEducation\nEnter your qualification and graduation date\nSkills\nEnter your skills'):type==='portfolio-templates'?t('اسم المشروع الأول\nوصف المشروع ودورك فيه\nاسم المشروع الثاني\nوصف المشروع ودورك فيه','First project name\nProject description and your role\nSecond project name\nProject description and your role'):t('حساب التواصل الأول\nحساب التواصل الثاني\nخدمة أو مهارة تقدمها','First social account\nSecond social account\nA service or skill you offer'),extra:type==='invoice-templates'?t('اسم العميل\nرقم الفاتورة\nتاريخ الفاتورة','Client name\nInvoice number\nInvoice date'):t('أضف معلومات إضافية أو روابط التواصل.','Add extra information or contact links.'),color:'#D51F2B'};
}
export function templateHtml(type:string,variant:number,v:TemplateValues,ar:boolean){
 const esc=escapeMarkup,t=(a:string,e:string)=>ar?a:e,color=/^#[a-f0-9]{6}$/i.test(v.color)?v.color:'#D51F2B';
 const heading=type==='cv-templates'?t('السيرة الذاتية','Curriculum Vitae'):type==='portfolio-templates'?t('أعمالي','Selected Work'):type==='media-kit-templates'?t('ميديا كيت','Media Kit'):type==='invoice-templates'?t('فاتورة','Invoice'):t('بروفايل','Profile');
 let details=`<div class="details">${v.details.split('\n').filter(Boolean).map(line=>`<p contenteditable="true">${esc(line)}</p>`).join('')}</div>`;
 if(type==='invoice-templates'){
  const rows=v.details.split('\n').filter(Boolean).map(line=>{const[name,q,p]=line.split('|');const quantity=Math.max(0,Number(q)||0),price=Math.max(0,Number(p)||0);return{name:name.trim(),quantity,price,total:quantity*price}});
  details=`<table><thead><tr><th>${t('الخدمة','Service')}</th><th>${t('الكمية','Qty')}</th><th>${t('السعر','Price')}</th><th>${t('المجموع','Total')}</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.quantity}</td><td>${r.price.toFixed(2)}</td><td>${r.total.toFixed(2)}</td></tr>`).join('')}</tbody></table><p class="total">${t('الإجمالي','Total')}: ${rows.reduce((s,r)=>s+r.total,0).toFixed(2)} SAR</p>`;
 }
 return`<!doctype html><html lang="${ar?'ar':'en'}" dir="${ar?'rtl':'ltr'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(v.name)} — ${heading}</title><style>*{box-sizing:border-box}body{margin:0;background:#e8e8e8;color:#222;font-family:Arial,sans-serif;line-height:1.75}.sheet{max-width:850px;margin:20px auto;background:white;min-height:1000px;display:${variant===2?'grid':'block'};grid-template-columns:250px 1fr}.intro{padding:45px;background:${variant===1?'#fff':color};color:${variant===1?'#222':'white'};border-bottom:${variant===1?'4px solid '+color:'none'}}.content{padding:40px}.eyebrow{letter-spacing:.14em;font-size:12px;text-transform:uppercase}h1{font-size:38px;line-height:1.3;margin:15px 0}h2{font-size:24px;border-bottom:2px solid ${color};padding-bottom:12px}.bio{white-space:pre-line}.details p{border-bottom:1px solid #ddd;padding:12px 0;margin:0;overflow-wrap:anywhere}.contact,.extra{white-space:pre-line;overflow-wrap:anywhere}.total{font-weight:bold;text-align:end}table{border-collapse:collapse;width:100%;font-size:14px}td,th{padding:12px 8px;border-bottom:1px solid #ddd;text-align:start}th{background:#f4f4f4;color:${color}}@media(max-width:600px){.sheet{display:block;margin:0}.intro,.content{padding:26px}h1{font-size:30px}}@page{size:A4;margin:12mm}@media print{body{background:white}.sheet{margin:0;min-height:0;max-width:none;print-color-adjust:exact;-webkit-print-color-adjust:exact}h2,table{break-inside:avoid}}</style></head><body><main class="sheet"><header class="intro"><p class="eyebrow">${heading}</p><h1 contenteditable="true">${esc(v.name)}</h1><p contenteditable="true">${esc(v.title)}</p><p class="contact" contenteditable="true">${esc(v.email)}</p></header><section class="content"><p class="bio" contenteditable="true">${esc(v.bio)}</p><h2>${heading}</h2>${details}<p class="extra" contenteditable="true">${esc(v.extra)}</p></section></main></body></html>`;
}
