import React,{useRef,useState}from'react';
import{templateDefaults,templateHtml,type TemplateValues}from'./templateDesign';
import{saveFile}from'./files';
import type{ResourceItem}from'./resourceCatalog';
export function TemplateEditor({type,item,isArabic}:{type:string;item:ResourceItem;isArabic:boolean}){
 const[v,setV]=useState(()=>({...templateDefaults(type,isArabic),color:item.colors[1]})),frame=useRef<HTMLIFrameElement>(null),html=templateHtml(type,item.variant,v,isArabic),t=(a:string,e:string)=>isArabic?a:e;
 const labels:Record<keyof TemplateValues,string>={name:t('الاسم أو اسم الجهة','Name or business'),title:t('المسمى أو المجال','Role or niche'),email:t('البريد أو وسيلة التواصل','Email or contact'),bio:t('النبذة','Introduction'),details:type==='invoice-templates'?t('الخدمات: كل سطر (اسم الخدمة | الكمية | السعر)','Items: one per line (Service | Quantity | Price)'):t('المحتوى والتفاصيل (كل فقرة في سطر)','Content and details (one paragraph per line)'),extra:type==='invoice-templates'?t('اسم العميل ورقم وتاريخ الفاتورة','Client, invoice number and date'):t('معلومات وروابط إضافية','Extra information and links'),color:t('اللون الأساسي','Accent color')};
 return <div className="grid gap-6 lg:grid-cols-[320px_1fr]"><form className="grid content-start gap-3" onSubmit={e=>e.preventDefault()}>{(Object.keys(labels)as(keyof TemplateValues)[]).map(key=><label key={key} className="text-xs text-gray-400">{labels[key]}{key==='color'?<input type="color" value={v.color} onChange={e=>setV({...v,color:e.target.value})} className="mt-2 block h-10 w-full"/>:['bio','details','extra'].includes(key)?<textarea rows={key==='details'?7:3} maxLength={4000} value={v[key]} onChange={e=>setV({...v,[key]:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-black p-3 text-sm text-white"/>:<input maxLength={180} value={v[key]} onChange={e=>setV({...v,[key]:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-black p-3 text-sm text-white"/>}</label>)}<button type="button" onClick={()=>saveFile(html,`${item.id}.html`,'text/html;charset=utf-8')} className="rounded-xl bg-[#D51F2B] p-3 text-sm font-bold">{t('تحميل القالب القابل للتعديل','Download editable template')}</button><button type="button" onClick={()=>frame.current?.contentWindow?.print()} className="rounded-xl border border-white/15 p-3 text-sm font-bold">{t('طباعة / حفظ PDF','Print / Save PDF')}</button><p className="text-[11px] leading-6 text-gray-500">{t('افتح ملف HTML في المتصفح وعدّل نصوصه، أو اختر حفظ PDF من نافذة الطباعة.','Open the HTML file in your browser to edit its text, or choose Save as PDF in the print dialog.')}</p></form><iframe ref={frame} title={t('معاينة القالب','Template preview')} srcDoc={html} sandbox="allow-same-origin allow-modals" className="h-[700px] w-full rounded-xl border border-white/10 bg-white"/></div>;
}
