import React,{useEffect,useState}from'react';
import{ImageDown,ArrowDown,Check,Copy}from'lucide-react';
export function ToolPreview({id,isArabic}:{id:string;isArabic:boolean}){
 const[qr,setQr]=useState('');useEffect(()=>{if(id==='qr-generator')import('qrcode').then(q=>q.toDataURL('https://saeedbinayidh.com',{width:180,margin:2,color:{dark:'#090909',light:'#ffffff'}})).then(setQr).catch(()=>{})},[id]);
 const box='rounded-xl border border-white/10 bg-[#151515] px-4 py-3';
 return <div className="relative mt-6 flex min-h-52 flex-col justify-center gap-3 overflow-hidden rounded-2xl border border-white/10 bg-[#080808] p-5" dir="ltr">
 {id==='username-generator'&&<><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#D51F2B]/20 text-xl text-[#ED1C2E]">@</span><div><p className="text-sm font-bold text-white">{isArabic?'اسمك · مجالك · لقبك':'Name · Niche · Nickname'}</p><p className="text-[10px] text-gray-500">{isArabic?'اقتراحات تناسب هويتك':'Ideas for your identity'}</p></div></div>{['omar.photo','by.omar','omar.studio'].map((x,i)=><div key={x} className={`${box} flex items-center justify-between`}><div><p className="text-sm font-bold text-white">@{x}</p><p className="mt-1 font-mono text-[10px] text-gray-500">instagram.com/{x}</p></div>{i===0?<Check className="h-4 w-4 text-[#ED1C2E]"/>:<Copy className="h-4 w-4 text-gray-500"/>}</div>)}</>}
 {id==='hashtag-generator'&&<><p className={`${box} text-sm text-gray-300`} dir={isArabic?'rtl':'ltr'}>{isArabic?'تصوير جوال في الطبيعة':'Mobile photography in nature'}</p><ArrowDown className="mx-auto h-4 w-4 text-[#ED1C2E]"/><div className="flex flex-wrap gap-2">{['#تصوير','#طبيعة','#photography','#mobilephotography','#تصوير_جوال','#nature'].map((x,i)=><span key={x} className={`rounded-lg border px-3 py-2 text-xs ${i<3?'border-[#D51F2B]/50 bg-[#D51F2B]/15 text-white':'border-white/10 text-gray-500'}`}>{x} {i<3&&'✓'}</span>)}</div><p className="mt-2 text-center text-[10px] text-gray-500">{isArabic?'اختر الهاشتاقات ثم انسخها':'Select your tags, then copy'}</p></>}
 {id==='image-compressor'&&<><div className="relative overflow-hidden rounded-xl"><img src="/assets/creator-nature/mountains-preview.webp" alt="" className="h-24 w-full object-cover"/><span className="absolute bottom-2 left-2 rounded-lg bg-black/80 px-2 py-1 text-[10px] text-white">JPG / PNG / WEBP</span></div><div className="flex items-center justify-between"><span className={`${box} text-sm text-gray-400`}>2.4 MB</span><ImageDown className="h-6 w-6 text-[#ED1C2E]"/><span className={`${box} text-sm font-bold text-white`}>250 KB</span></div><p className="text-center text-[10px] text-gray-500">{isArabic?'مثال توضيحي · حدد الحجم المناسب لك':'Illustrative example · Set your target size'}</p></>}
 {id==='qr-generator'&&<><div className="flex items-center justify-center gap-5"><div className="rounded-xl bg-white p-2">{qr?<img src={qr} alt={isArabic?'باركود تجريبي للموقع':'Example website QR'} className="h-28 w-28"/>:<span className="block h-28 w-28"/>}</div><div className="space-y-3"><span className="block rounded-lg border border-white/10 px-4 py-2 text-xs text-gray-400">PNG</span><span className="block rounded-lg border border-white/10 px-4 py-2 text-xs text-gray-400">SVG</span></div></div><p className={`${box} truncate text-center font-mono text-[10px] text-gray-400`}>https://saeedbinayidh.com</p></>}
 </div>;
}
