import React, { useState } from 'react';
import { BookOpen, ChevronDown, ChevronUp, FileText, Image as ImageIcon, Inbox, Plus, Search, Trash2, Upload, X } from 'lucide-react';
import { useCMS } from '../../context/CMSContext';

const input='w-full rounded-xl border border-white/10 bg-[#090909] px-3 py-3 text-sm text-white outline-none focus:border-[#D51F2B]';
const box='rounded-2xl border border-white/10 bg-[#111] p-4';
const pages=[['home','الرئيسية'],['services','الخدمات'],['news','الأخبار'],['blog','المدونة'],['works','الأعمال'],['resources','الأدوات'],['about','عن سعيد'],['contact','تواصل معنا'],['centerhelp','سنترهلب']];

export const AdvancedAdminControls:React.FC=()=>{
 const cms=useCMS(); const {data,updateGlobal,updateHero,addMedia,deleteMedia,updateSubmissionStatus,deleteSubmission}=cms;
 const [open,setOpen]=useState(false); const [section,setSection]=useState('buttons');
 const g:any=data.global; const headers:any=g.pageHeaders||{}; const seo:any=g.seo||{}; const footer:any=g.footer||{about:data.global.description,privacyLabel:'سياسة الخصوصية',termsLabel:'الشروط والأحكام'};
 const patchHeader=(id:string,p:any)=>updateGlobal({pageHeaders:{...headers,[id]:{...(headers[id]||{}),...p}}} as any);
 const patchSeo=(id:string,p:any)=>updateGlobal({seo:{...seo,[id]:{...(seo[id]||{}),...p}}} as any);
 const read=(file:File|undefined,done:(v:string)=>void)=>{if(!file)return;const r=new FileReader();r.onload=()=>typeof r.result==='string'&&done(r.result);r.readAsDataURL(file)};
 const addMediaFile=(file:File|undefined)=>read(file,url=>addMedia({id:`media-${Date.now()}`,name:file?.name||'صورة',url,type:'image',size:file?`${Math.ceil(file.size/1024)} KB`:'',uploadDate:new Date().toLocaleDateString('ar-SA')}));
 const nav=[['buttons','أزرار البنر',Plus],['pages','عناوين الصفحات',FileText],['footer','الفوتر',BookOpen],['seo','SEO',Search],['media','مكتبة الوسائط',ImageIcon],['inbox','الوارد',Inbox]] as const;
 return <>
  <button type="button" onClick={()=>setOpen(true)} className="fixed bottom-24 right-4 z-[79] rounded-2xl border border-white/15 bg-[#171717] px-4 py-3 text-xs font-black text-white shadow-2xl lg:bottom-6 lg:right-[19rem]">إدارة متقدمة</button>
  {open&&<div className="fixed inset-0 z-[100] bg-black/80 p-0 sm:p-4" dir="rtl"><div className="mx-auto flex h-dvh max-w-5xl flex-col overflow-hidden bg-[#080808] sm:h-[calc(100dvh-32px)] sm:rounded-3xl sm:border sm:border-white/10">
   <div className="flex items-center justify-between border-b border-white/10 p-4"><div><h2 className="text-xl font-black">التحكم المتقدم</h2><p className="text-xs text-gray-500">كل التعديلات تحتاج زر «حفظ التعديلات» أسفل اللوحة.</p></div><button onClick={()=>setOpen(false)} className="rounded-xl bg-[#181818] p-3"><X className="h-5 w-5"/></button></div>
   <div className="flex gap-2 overflow-x-auto border-b border-white/10 p-3">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setSection(id)} className={`shrink-0 rounded-xl px-4 py-2.5 text-xs font-bold ${section===id?'bg-[#D51F2B]':'bg-[#151515]'}`}><Icon className="ml-2 inline h-4 w-4"/>{label}</button>)}</div>
   <div className="grow overflow-y-auto p-4 sm:p-6">
    {section==='buttons'&&<div className="space-y-4"><div className="flex items-center justify-between"><h3 className="font-black">أزرار البنر الرئيسي</h3><button onClick={()=>updateHero({buttons:[...data.hero.buttons,{label:'زر جديد',url:'/',isPrimary:false}]})} className="rounded-xl bg-[#D51F2B] px-4 py-2 text-xs font-bold"><Plus className="ml-1 inline h-4 w-4"/>إضافة زر</button></div>{data.hero.buttons.map((b,i)=><div key={i} className={box}><div className="grid gap-3 sm:grid-cols-2"><input className={input} value={b.label} onChange={e=>updateHero({buttons:data.hero.buttons.map((x,j)=>j===i?{...x,label:e.target.value}:x)})} placeholder="اسم الزر"/><input className={input} value={b.url} onChange={e=>updateHero({buttons:data.hero.buttons.map((x,j)=>j===i?{...x,url:e.target.value}:x)})} placeholder="الرابط"/></div><div className="mt-3 flex gap-2"><button onClick={()=>updateHero({buttons:data.hero.buttons.map((x,j)=>j===i?{...x,isPrimary:!x.isPrimary}:x)})} className="rounded-lg bg-[#202020] px-3 py-2 text-xs">{b.isPrimary?'رئيسي':'ثانوي'}</button><button onClick={()=>updateHero({buttons:data.hero.buttons.filter((_,j)=>j!==i)})} className="rounded-lg border border-red-500/30 px-3 py-2 text-red-400"><Trash2 className="h-4 w-4"/></button></div></div>)}</div>}
    {section==='pages'&&<div className="space-y-4"><h3 className="font-black">عناوين وأوصاف الصفحات</h3>{pages.map(([id,label])=><div key={id} className={box}><div className="mb-3 font-bold text-[#D51F2B]">{label}</div><input className={input} value={headers[id]?.badge||''} onChange={e=>patchHeader(id,{badge:e.target.value})} placeholder="الشارة"/><input className={`${input} mt-2`} value={headers[id]?.title||''} onChange={e=>patchHeader(id,{title:e.target.value})} placeholder="عنوان الصفحة"/><textarea className={`${input} mt-2 min-h-24`} value={headers[id]?.description||''} onChange={e=>patchHeader(id,{description:e.target.value})} placeholder="وصف الصفحة"/></div>)}</div>}
    {section==='footer'&&<div className="space-y-4"><h3 className="font-black">الفوتر</h3><div className={box}><label className="mb-2 block text-xs">وصف الفوتر</label><textarea className={`${input} min-h-28`} value={footer.about||''} onChange={e=>updateGlobal({footer:{...footer,about:e.target.value}} as any)}/><label className="mb-2 mt-4 block text-xs">حقوق النشر</label><input className={input} value={data.global.copyrightText} onChange={e=>updateGlobal({copyrightText:e.target.value})}/><div className="mt-3 grid gap-3 sm:grid-cols-2"><input className={input} value={footer.privacyLabel||''} onChange={e=>updateGlobal({footer:{...footer,privacyLabel:e.target.value}} as any)} placeholder="اسم رابط الخصوصية"/><input className={input} value={footer.termsLabel||''} onChange={e=>updateGlobal({footer:{...footer,termsLabel:e.target.value}} as any)} placeholder="اسم رابط الشروط"/></div></div></div>}
    {section==='seo'&&<div className="space-y-4"><h3 className="font-black">SEO لكل صفحة</h3>{pages.map(([id,label])=><div key={id} className={box}><div className="mb-3 font-bold text-[#D51F2B]">{label}</div><input className={input} value={seo[id]?.title||''} onChange={e=>patchSeo(id,{title:e.target.value})} placeholder="عنوان SEO"/><textarea className={`${input} mt-2 min-h-20`} value={seo[id]?.description||''} onChange={e=>patchSeo(id,{description:e.target.value})} placeholder="وصف SEO"/><input className={`${input} mt-2`} value={seo[id]?.image||''} onChange={e=>patchSeo(id,{image:e.target.value})} placeholder="صورة المشاركة"/></div>)}</div>}
    {section==='media'&&<div className="space-y-4"><div className="flex items-center justify-between"><h3 className="font-black">مكتبة الوسائط</h3><label className="cursor-pointer rounded-xl bg-[#D51F2B] px-4 py-2 text-xs font-bold"><Upload className="ml-1 inline h-4 w-4"/>رفع صورة<input type="file" accept="image/*" className="hidden" onChange={e=>addMediaFile(e.target.files?.[0])}/></label></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.media.map(m=><div key={m.id} className={box}>{m.type==='image'&&<img src={m.url} alt={m.name} className="mb-3 h-36 w-full rounded-xl object-cover"/>}<div className="truncate text-xs font-bold">{m.name}</div><input readOnly value={m.url} className={`${input} mt-2 text-[10px]`}/><button onClick={()=>deleteMedia(m.id)} className="mt-2 rounded-lg border border-red-500/30 p-2 text-red-400"><Trash2 className="h-4 w-4"/></button></div>)}</div></div>}
    {section==='inbox'&&<div className="space-y-4"><h3 className="font-black">الاقتراحات والشكاوى والرسائل</h3>{data.submissions.length===0&&<div className={box}>لا توجد رسائل واردة.</div>}{data.submissions.map(s=><div key={s.id} className={box}><div className="flex items-start justify-between gap-3"><div><div className="font-black">{s.type==='complaint'?'شكوى':s.type==='suggestion'?'اقتراح':'رسالة تواصل'} — {s.name}</div><div className="mt-1 text-xs text-gray-500">{s.email} • {s.date}</div></div><button onClick={()=>deleteSubmission(s.id)} className="text-red-400"><Trash2 className="h-4 w-4"/></button></div><p className="my-3 whitespace-pre-wrap text-sm text-gray-300">{s.message}</p><select className={input} value={s.status} onChange={e=>updateSubmissionStatus(s.id,e.target.value as any)}><option>جديد</option><option>قيد المراجعة</option><option>تم الحل</option><option>مغلق</option></select><textarea className={`${input} mt-2 min-h-20`} value={s.adminNotes||''} onChange={e=>updateSubmissionStatus(s.id,s.status,e.target.value)} placeholder="ملاحظات الإدارة"/></div>)}</div>}
   </div>
  </div></div>}
 </>;
};
