import React,{useMemo,useState} from 'react';
import { ChevronDown,ChevronUp,Image as ImageIcon,Link as LinkIcon,Plus,Save,Trash2,Upload,Video,X } from 'lucide-react';
import { useCMS } from '../../context/CMSContext';
import { defaultSaeedPlatform, PlatformItem, SaeedPlatform } from '../SaeedPlatformSection';

const input='w-full rounded-xl border border-white/10 bg-[#090909] px-3 py-3 text-sm text-white outline-none focus:border-[#D51F2B]';
const box='rounded-2xl border border-white/10 bg-[#111] p-4';

export const SaeedPlatformAdmin:React.FC=()=>{
 const {data,updateGlobal,saveChanges,hasUnsavedChanges,isSaving}=useCMS();
 const [open,setOpen]=useState(false); const [active,setActive]=useState<string|null>(null); const [notice,setNotice]=useState('');
 const platform:SaeedPlatform=useMemo(()=>((data.global as any).saeedPlatform||defaultSaeedPlatform),[data.global]);
 const patch=(next:Partial<SaeedPlatform>)=>updateGlobal({saeedPlatform:{...platform,...next}} as any);
 const patchItem=(id:string,next:Partial<PlatformItem>)=>patch({items:platform.items.map(x=>x.id===id?{...x,...next}:x)});
 const addItem=()=>{const item:PlatformItem={id:`custom-${Date.now()}`,title:'قسم جديد',description:'',badge:'جديد',imageUrl:'',videoUrl:'',enabled:true,order:(platform.items.length||0)+1,buttons:[]};patch({items:[...platform.items,item]});setActive(item.id)};
 const del=(id:string)=>patch({items:platform.items.filter(x=>x.id!==id)});
 const move=(id:string,dir:-1|1)=>{const items=[...platform.items].sort((a,b)=>a.order-b.order);const i=items.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=items.length)return;[items[i],items[j]]=[items[j],items[i]];patch({items:items.map((x,k)=>({...x,order:k+1}))})};
 const addButton=(id:string)=>{const item=platform.items.find(x=>x.id===id);if(!item)return;patchItem(id,{buttons:[...(item.buttons||[]),{label:'زر جديد',url:'#',enabled:true}]})};
 const patchButton=(id:string,i:number,next:any)=>{const item=platform.items.find(x=>x.id===id);if(!item)return;patchItem(id,{buttons:(item.buttons||[]).map((b,j)=>j===i?{...b,...next}:b)})};
 const deleteButton=(id:string,i:number)=>{const item=platform.items.find(x=>x.id===id);if(!item)return;patchItem(id,{buttons:(item.buttons||[]).filter((_,j)=>j!==i)})};
 const readFile=(file:File|undefined,cb:(v:string)=>void)=>{if(!file)return;if(file.size>5*1024*1024){setNotice('الملف أكبر من 5MB. استخدم رابط خارجي للمقاطع الكبيرة.');return;}const r=new FileReader();r.onload=()=>typeof r.result==='string'&&cb(r.result);r.readAsDataURL(file)};
 const save=async()=>{const ok=await saveChanges();setNotice(ok?'تم حفظ أقسام عالم سعيد.':'تعذر الحفظ، حاول مرة ثانية.')};
 return <>
  <button type="button" onClick={()=>setOpen(true)} className="fixed bottom-40 right-4 z-[79] rounded-2xl border border-[#D51F2B]/40 bg-[#D51F2B] px-4 py-3 text-xs font-black text-white shadow-2xl lg:bottom-20 lg:right-[19rem]">إدارة عالم سعيد</button>
  {open&&<div className="fixed inset-0 z-[110] bg-black/85 p-0 sm:p-4" dir="rtl"><div className="mx-auto flex h-dvh max-w-6xl flex-col overflow-hidden bg-[#080808] sm:h-[calc(100dvh-32px)] sm:rounded-3xl sm:border sm:border-white/10">
   <div className="flex items-center justify-between gap-3 border-b border-white/10 p-4"><div><h2 className="text-xl font-black">إدارة عالم سعيد</h2><p className="mt-1 text-xs text-gray-500">تحكم كامل في الأقسام، الصور، المقاطع، الروابط والأزرار.</p></div><button onClick={()=>setOpen(false)} className="rounded-xl bg-[#181818] p-3"><X className="h-5 w-5"/></button></div>
   <div className="grow overflow-y-auto p-4 sm:p-6">
    {notice&&<div className="mb-4 rounded-xl border border-white/10 bg-[#151515] p-3 text-xs">{notice}</div>}
    <div className={`${box} mb-4`}><div className="mb-4 flex items-center justify-between"><div className="font-black">إعدادات القسم الرئيسي</div><button onClick={()=>patch({enabled:!platform.enabled})} className={`rounded-xl px-4 py-2 text-xs font-bold ${platform.enabled?'bg-green-950 text-green-400':'bg-[#222] text-gray-400'}`}>{platform.enabled?'ظاهر بالموقع':'مخفي'}</button></div><div className="grid gap-3 sm:grid-cols-2"><input className={input} value={platform.badge} onChange={e=>patch({badge:e.target.value})} placeholder="الشارة"/><input className={input} value={platform.title} onChange={e=>patch({title:e.target.value})} placeholder="العنوان"/></div><textarea className={`${input} mt-3 min-h-24`} value={platform.description} onChange={e=>patch({description:e.target.value})} placeholder="الوصف"/></div>
    <div className="mb-4 flex items-center justify-between"><h3 className="font-black">الأقسام ({platform.items.length})</h3><button onClick={addItem} className="rounded-xl bg-[#D51F2B] px-4 py-2 text-xs font-bold"><Plus className="ml-1 inline h-4 w-4"/>إضافة قسم</button></div>
    <div className="space-y-3">{[...platform.items].sort((a,b)=>a.order-b.order).map(item=><div key={item.id} className={box}>
     <div className="flex items-center gap-2"><button onClick={()=>setActive(active===item.id?null:item.id)} className="min-w-0 grow text-right"><div className="truncate font-black">{item.title}</div><div className="mt-1 text-[11px] text-gray-500">{item.badge} • ترتيب {item.order}</div></button><button onClick={()=>patchItem(item.id,{enabled:!item.enabled})} className={`rounded-lg px-3 py-2 text-[11px] ${item.enabled?'bg-green-950 text-green-400':'bg-[#222] text-gray-500'}`}>{item.enabled?'ظاهر':'مخفي'}</button><button onClick={()=>move(item.id,-1)} className="rounded-lg bg-[#1a1a1a] p-2"><ChevronUp className="h-4 w-4"/></button><button onClick={()=>move(item.id,1)} className="rounded-lg bg-[#1a1a1a] p-2"><ChevronDown className="h-4 w-4"/></button><button onClick={()=>del(item.id)} className="rounded-lg border border-red-500/20 p-2 text-red-400"><Trash2 className="h-4 w-4"/></button></div>
     {active===item.id&&<div className="mt-4 border-t border-white/10 pt-4"><div className="grid gap-3 sm:grid-cols-2"><input className={input} value={item.title} onChange={e=>patchItem(item.id,{title:e.target.value})} placeholder="اسم القسم"/><input className={input} value={item.badge} onChange={e=>patchItem(item.id,{badge:e.target.value})} placeholder="الشارة"/></div><textarea className={`${input} mt-3 min-h-24`} value={item.description} onChange={e=>patchItem(item.id,{description:e.target.value})} placeholder="الوصف"/>
      <div className="mt-4 grid gap-3 lg:grid-cols-2"><div><label className="mb-2 block text-xs font-bold"><ImageIcon className="ml-1 inline h-4 w-4"/>صورة</label><input className={input} value={item.imageUrl} onChange={e=>patchItem(item.id,{imageUrl:e.target.value})} placeholder="رابط الصورة"/><label className="mt-2 inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#191919] px-3 py-2 text-xs"><Upload className="h-4 w-4"/>رفع صورة<input type="file" accept="image/*" className="hidden" onChange={e=>readFile(e.target.files?.[0],v=>patchItem(item.id,{imageUrl:v}))}/></label>{item.imageUrl&&<img src={item.imageUrl} alt="" className="mt-3 h-28 w-full rounded-xl object-cover"/>}</div>
       <div><label className="mb-2 block text-xs font-bold"><Video className="ml-1 inline h-4 w-4"/>مقطع</label><input className={input} value={item.videoUrl} onChange={e=>patchItem(item.id,{videoUrl:e.target.value})} placeholder="رابط MP4 أو رابط مباشر"/><label className="mt-2 inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#191919] px-3 py-2 text-xs"><Upload className="h-4 w-4"/>رفع مقطع صغير<input type="file" accept="video/*" className="hidden" onChange={e=>readFile(e.target.files?.[0],v=>patchItem(item.id,{videoUrl:v}))}/></label><div className="mt-2 text-[10px] text-gray-600">الرفع المباشر حتى 5MB؛ للمقاطع الكبيرة استخدم رابط خارجي.</div></div></div>
      <div className="mt-5"><div className="mb-3 flex items-center justify-between"><div className="text-xs font-black"><LinkIcon className="ml-1 inline h-4 w-4"/>الأزرار والروابط</div><button onClick={()=>addButton(item.id)} className="rounded-lg bg-[#D51F2B] px-3 py-2 text-[11px] font-bold"><Plus className="ml-1 inline h-3.5 w-3.5"/>إضافة زر</button></div><div className="space-y-2">{(item.buttons||[]).map((b,i)=><div key={i} className="grid gap-2 rounded-xl border border-white/5 bg-[#0b0b0b] p-3 sm:grid-cols-[1fr_2fr_auto_auto]"><input className={input} value={b.label} onChange={e=>patchButton(item.id,i,{label:e.target.value})} placeholder="اسم الزر"/><input className={input} value={b.url} onChange={e=>patchButton(item.id,i,{url:e.target.value})} placeholder="الرابط"/><button onClick={()=>patchButton(item.id,i,{enabled:!b.enabled})} className="rounded-lg bg-[#191919] px-3 text-[11px]">{b.enabled?'مفعّل':'متوقف'}</button><button onClick={()=>deleteButton(item.id,i)} className="rounded-lg text-red-400"><Trash2 className="mx-auto h-4 w-4"/></button></div>)}</div></div>
     </div>}
    </div>)}</div>
   </div>
   <div className="flex items-center justify-between border-t border-white/10 bg-[#0c0c0c] p-4"><div className="text-xs text-gray-500">{hasUnsavedChanges?'عندك تعديلات غير محفوظة':'كل التعديلات محفوظة'}</div><button disabled={isSaving} onClick={save} className="rounded-xl bg-[#D51F2B] px-5 py-3 text-xs font-black disabled:opacity-50"><Save className="ml-2 inline h-4 w-4"/>{isSaving?'جاري الحفظ...':'حفظ التعديلات'}</button></div>
  </div></div>}
 </>;
};
