const fs=require('fs');const path=require('path');
const PROJECT_FALLBACK=path.join(__dirname,'..','data','cms.json');
function pickPersistentPath(){if(process.env.CMS_DATA_FILE)return process.env.CMS_DATA_FILE;for(const file of['/var/data/saeed-cms.json','/data/saeed-cms.json']){try{const dir=path.dirname(file);fs.mkdirSync(dir,{recursive:true,mode:0o700});fs.accessSync(dir,fs.constants.W_OK);return file}catch{}}return PROJECT_FALLBACK}
const CMS_DATA_FILE=pickPersistentPath();
function migrateLegacyFileIfNeeded(){if(CMS_DATA_FILE===PROJECT_FALLBACK||fs.existsSync(CMS_DATA_FILE)||!fs.existsSync(PROJECT_FALLBACK))return;try{const dir=path.dirname(CMS_DATA_FILE);fs.mkdirSync(dir,{recursive:true,mode:0o700});fs.copyFileSync(PROJECT_FALLBACK,CMS_DATA_FILE);try{fs.chmodSync(CMS_DATA_FILE,0o600)}catch{}console.log(`Migrated CMS data to persistent storage: ${CMS_DATA_FILE}`)}catch(error){console.error('Failed to migrate legacy CMS data',error)}}
migrateLegacyFileIfNeeded();console.log(`CMS data file: ${CMS_DATA_FILE}`);
function load(){if(!fs.existsSync(CMS_DATA_FILE))return null;try{const raw=fs.readFileSync(CMS_DATA_FILE,'utf8');if(!raw.trim())return null;const parsed=JSON.parse(raw);return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed:null}catch(error){console.error('Failed to load CMS data safely:',error?.message||error);return null}}
function save(data){if(!data||typeof data!=='object'||Array.isArray(data))throw new Error('Invalid CMS payload');const dir=path.dirname(CMS_DATA_FILE);if(!fs.existsSync(dir))fs.mkdirSync(dir,{recursive:true,mode:0o700});const temp=`${CMS_DATA_FILE}.${process.pid}.${Date.now()}.tmp`;try{fs.writeFileSync(temp,JSON.stringify(data,null,2),{mode:0o600,flag:'wx'});fs.renameSync(temp,CMS_DATA_FILE);try{fs.chmodSync(CMS_DATA_FILE,0o600)}catch{}}catch(error){try{if(fs.existsSync(temp))fs.unlinkSync(temp)}catch{}throw error}}
module.exports={load,save,CMS_DATA_FILE};
