import React,{useState}from'react';
import{useParams}from'react-router-dom';
import{useLanguage}from'../context/LanguageContext';
import{ResourceBackButton}from'../components/ResourceBackButton';
import{creatorTools}from'../features/creator/toolCatalog';
import{usernames,hashtags,validLink}from'../features/creator/toolLogic';
import{copyText,saveFile,compressImage}from'../features/creator/files';
const input='mt-2 w-full rounded-xl border border-white/15 bg-[#080808] px-4 py-3 text-sm text-white outline-none focus:border-[#D51F2B]';
const button='rounded-xl bg-[#D51F2B] px-5 py-3 text-sm font-bold text-white disabled:opacity-50';
export function CreatorToolPage({toolSlug}:{toolSlug?:string}){
 const params=useParams(),slug=toolSlug||params.slug,{isArabic}=useLanguage(),t=(ar:string,en:string)=>isArabic?ar:en,tool=creatorTools.find(x=>x.id===slug);
 const[name,setName]=useState(''),[field,setField]=useState(''),[nickname,setNickname]=useState(''),[topic,setTopic]=useState(''),[suggestions,setSuggestions]=useState<string[]>([]),[selected,setSelected]=useState<string[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const[file,setFile]=useState<File|null>(null),[target,setTarget]=useState(250),[edge,setEdge]=useState(1920),[format,setFormat]=useState<'image/jpeg'|'image/webp'>('image/jpeg'),[compressed,setCompressed]=useState<{blob:Blob;width:number;height:number}|null>(null);
 const[url,setUrl]=useState(''),[qr,setQr]=useState<{png:string;svg:string;url:string}|null>(null);
 const copy=async(value:string)=>{try{await copyText(value);setNotice(t('تم النسخ','Copied'))}catch{setNotice(t('تعذر النسخ، انسخ النص يدويًا.','Copy failed. Select and copy manually.'))}};
 if(!tool)return <div className="px-5 pb-20 pt-28"><ResourceBackButton tools/><h1>{t('الأداة غير موجودة','Tool not found')}</h1></div>;
 return <div key={slug} className="min-h-screen pb-24 pt-28" dir={isArabic?'rtl':'ltr'}><div className="mx-auto max-w-4xl px-4"><ResourceBackButton tools/><header className="mb-8 text-center"><p className="text-xs text-[#D51F2B]">{t('أدوات سعيد','Saeed Tools')}</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">{t(tool.ar,tool.en)}</h1><p className="mt-4 text-sm text-gray-400">{t(tool.desc,tool.descEn)}</p></header><div className="rounded-3xl border border-white/10 bg-[#111] p-5 sm:p-8">
 {slug==='username-generator'&&<><form className="grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const items=usernames(name,field,nickname);setSuggestions(items);setNotice(items.length?'':t('اكتب اسمًا ومجالًا واضحين.','Enter a readable name and niche.'))}}><label>{t('الاسم *','Name *')}<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} className={input}/></label><label>{t('المجال *','Niche *')}<input required maxLength={80} value={field} onChange={e=>setField(e.target.value)} className={input}/></label><label>{t('اللقب (اختياري)','Nickname (optional)')}<input maxLength={40} value={nickname} onChange={e=>setNickname(e.target.value)} className={input}/></label><button className={`${button} self-end`}>{t('اقترح يوزرات','Suggest usernames')}</button></form><p className="mt-4 text-xs leading-6 text-gray-500">{t('الاقتراحات لا تؤكد توفر اليوزر. تحقق منه في التطبيق قبل اعتماده.','Suggestions do not check availability. Verify your choice in the app.')}</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{suggestions.map(s=><button key={s} type="button" onClick={()=>copy(s)} className="flex justify-between rounded-xl border border-white/10 bg-black/30 p-4"><span dir="ltr">@{s}</span><span className="text-xs text-[#ED1C2E]">{t('نسخ','Copy')}</span></button>)}</div></>}
 {slug==='hashtag-generator'&&<><form onSubmit={e=>{e.preventDefault();setSuggestions(hashtags(topic));setSelected([]);setNotice('')}}><label>{t('موضوع المحتوى *','Content topic *')}<textarea required maxLength={200} value={topic} onChange={e=>setTopic(e.target.value)} className={input}/></label><button className={`${button} mt-4`}>{t('توليد الهاشتاقات','Generate hashtags')}</button></form>{suggestions.length>0&&<><div className="my-6 flex flex-wrap gap-2">{suggestions.map(s=><button key={s} type="button" aria-pressed={selected.includes(s)} onClick={()=>setSelected(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s])} className={`rounded-xl border px-3 py-2 text-sm ${selected.includes(s)?'border-[#D51F2B] bg-[#D51F2B]/20':'border-white/15'}`}>{s}</button>)}</div><button type="button" className="me-3 rounded-xl border border-white/20 px-4 py-3" onClick={()=>setSelected(suggestions)}>{t('اختيار الكل','Select all')}</button><button disabled={!selected.length} type="button" className={button} onClick={()=>copy(selected.join(' '))}>{t(`نسخ المختار (${selected.length})`,`Copy selected (${selected.length})`)}</button><p className="mt-4 break-words text-sm text-gray-400">{selected.join(' ')}</p></>}</>}
 {slug==='image-compressor'&&<><form onSubmit={async e=>{e.preventDefault();if(!file)return;setBusy(true);setNotice('');setCompressed(null);try{setCompressed(await compressImage(file,target,edge,format))}catch{setNotice(t('تعذر ضغط الصورة. استخدم JPG أو PNG أو WEBP حتى 20 ميجابايت، أو ارفع الحجم المطلوب.','Compression failed. Use JPG, PNG or WEBP up to 20 MB, or increase the target size.'))}finally{setBusy(false)}}} className="grid gap-5 sm:grid-cols-2"><label className="sm:col-span-2">{t('الصورة *','Image *')}<input type="file" required accept="image/jpeg,image/png,image/webp" className={input} onChange={e=>{setFile(e.target.files?.[0]||null);setCompressed(null)}}/></label><label>{t('الحجم الأقصى (كيلوبايت)','Maximum size (KB)')}<input type="number" required min={10} max={10000} value={target} onChange={e=>{setTarget(Number(e.target.value));setCompressed(null)}} className={input}/></label><label>{t('أقصى طول أو عرض (بكسل)','Maximum edge (pixels)')}<input type="number" required min={100} max={4096} value={edge} onChange={e=>{setEdge(Number(e.target.value));setCompressed(null)}} className={input}/></label><label>{t('الصيغة','Format')}<select className={input} value={format} onChange={e=>{setFormat(e.target.value as typeof format);setCompressed(null)}}><option value="image/jpeg">JPG</option><option value="image/webp">WEBP</option></select></label><button disabled={busy||!file} className={`${button} self-end`}>{busy?t('جارٍ الضغط…','Compressing…'):t('ضغط الصورة','Compress image')}</button></form><p className="mt-4 text-xs leading-6 text-gray-500">{t('الصورة تُعالج على جهازك. قد تقل الأبعاد للوصول للحجم المطلوب. شفافية PNG تتحول إلى خلفية بيضاء عند اختيار JPG.','The image stays on your device. Dimensions may be reduced to meet the target. JPG replaces transparency with white.')}</p>{compressed&&<div className="mt-6 rounded-xl border border-white/10 p-4"><p dir="ltr">{Math.ceil((file?.size||0)/1024)} KB → {(compressed.blob.size/1024).toFixed(1)} KB · {compressed.width} × {compressed.height}</p><button type="button" className={`${button} mt-4`} onClick={()=>saveFile(compressed.blob,`compressed.${compressed.blob.type==='image/webp'?'webp':'jpg'}`)}>{t('تحميل الصورة','Download image')}</button></div>}</>}
 {slug==='qr-generator'&&<><form onSubmit={async e=>{e.preventDefault();setBusy(true);setQr(null);setNotice('');try{const link=validLink(url);if(link.length>1800)throw Error('long');const QRCode=(await import('qrcode')).default;const options={errorCorrectionLevel:'M' as const,margin:4,width:1024,color:{dark:'#000000',light:'#ffffff'}};const[png,svg]=await Promise.all([QRCode.toDataURL(link,options),QRCode.toString(link,{...options,type:'svg'})]);setQr({png,svg,url:link})}catch{setNotice(t('أدخل رابط HTTP أو HTTPS صالحًا وأقصر من 1800 حرف.','Enter a valid HTTP or HTTPS link under 1800 characters.'))}finally{setBusy(false)}}}><label>{t('رابط المنصة *','Platform link *')}<input type="url" required maxLength={1800} dir="ltr" placeholder="https://instagram.com/username" value={url} onChange={e=>setUrl(e.target.value)} className={input}/></label><button disabled={busy} className={`${button} mt-4`}>{busy?t('جارٍ التوليد…','Generating…'):t('توليد الباركود','Generate QR code')}</button></form>{qr&&<div className="mt-6 text-center"><img src={qr.png} alt={t('باركود الرابط','Link QR code')} className="mx-auto w-64 rounded-xl"/><p dir="ltr" className="my-4 break-all text-xs text-gray-400">{qr.url}</p><button type="button" className={`${button} me-3`} onClick={()=>{const a=document.createElement('a');a.href=qr.png;a.download='link-qr.png';a.click()}}>PNG</button><button type="button" className={button} onClick={()=>saveFile(qr.svg,'link-qr.svg','image/svg+xml')}>SVG</button></div>}</>}
 {notice&&<p role="status" className="mt-5 text-sm text-[#ED1C2E]">{notice}</p>}
 </div></div></div>;
}
