import React from 'react';
import {ArrowRight,Briefcase,Newspaper,Calendar,Tag,FileText,CheckCircle2} from 'lucide-react';
import {useNavigate,useParams} from 'react-router-dom';

type Detail={title:string;description:string;type:'work'|'news';overview:string;category:string;date:string;status:string;details:string[]};

const details:Record<string,Detail>={
  'work/demo-work-1':{type:'work',title:'حملة تسويقية تجريبية',description:'نموذج عمل تجريبي يوضح طريقة عرض المشروع والنتائج.',overview:'صفحة تفصيلية للعمل تعرض فكرته، الهدف منه، نطاق التنفيذ، حالة المشروع، وأبرز المعلومات المرتبطة به. البيانات الحالية تجريبية فقط حتى إضافة العمل الحقيقي من لوحة التحكم.',category:'تسويق رقمي',date:'2026',status:'نموذج تجريبي',details:['فكرة العمل وأهدافه','الخدمات التي تم تنفيذها','النتائج والمخرجات','الصور والملفات والروابط المرتبطة بالعمل']},
  'work/demo-work-2':{type:'work',title:'واجهة مشروع تجريبية',description:'نموذج لتصميم واجهة رقمية مع تفاصيل مختصرة.',overview:'هذه الصفحة مخصصة لعرض تفاصيل مشروع تصميم واجهة رقمية، وتشمل نبذة المشروع ودور سعيد ونطاق العمل والنتائج والمواد المرتبطة بالمشروع.',category:'واجهات رقمية',date:'2026',status:'نموذج تجريبي',details:['نبذة كاملة عن المشروع','دور سعيد في المشروع','تفاصيل التصميم والتنفيذ','النتيجة النهائية وروابط المشروع']},
  'work/demo-work-3':{type:'work',title:'تغطية فعالية تجريبية',description:'نموذج لتغطية ميدانية مع معلومات العمل.',overview:'صفحة تفصيلية لتغطية فعالية، تعرض الجهة ونوع التغطية ومكانها وتاريخها والمحتوى الذي تم إنتاجه والنتائج المرتبطة بها.',category:'تغطية إعلامية',date:'2026',status:'نموذج تجريبي',details:['بيانات الجهة والفعالية','نوع ومكان التغطية','الصور والمقاطع المنتجة','أبرز نتائج التغطية']},
  'news/demo-news-1':{type:'news',title:'إعلان مشروع جديد',description:'خبر تجريبي يوضح شكل أخبار المشاريع والإعلانات.',overview:'صفحة الخبر الكاملة، وفيها نص الخبر وتفاصيل الإعلان والمعلومات المرتبطة بالمشروع وروابطه ومواده. هذا المحتوى تجريبي حتى إضافة الخبر الحقيقي.',category:'إعلانات المشاريع',date:'2026',status:'خبر تجريبي',details:['تفاصيل الإعلان','نبذة عن المشروع','موعد الإطلاق أو التحديث','الروابط والمواد المرتبطة بالخبر']},
  'news/demo-news-2':{type:'news',title:'تغطية فعالية جديدة',description:'خبر تجريبي عن تغطية أو فعالية شارك فيها سعيد.',overview:'صفحة خبر كاملة لتغطية فعالية، تعرض تفاصيل المشاركة أو التغطية والجهة والموقع والتاريخ وأبرز ما حدث والمواد المرتبطة بها.',category:'التغطيات',date:'2026',status:'خبر تجريبي',details:['تفاصيل الفعالية','الجهة والموقع','أبرز أحداث التغطية','الصور والمقاطع والروابط']},
  'news/demo-news-3':{type:'news',title:'تحديث جديد في الموقع',description:'خبر تجريبي عن تحديث أو ميزة جديدة تمت إضافتها.',overview:'صفحة خبر كاملة لتحديثات الموقع، تعرض الميزة الجديدة وما تغير وكيف يستفيد منها الزائر وأي ملاحظات أو تفاصيل إضافية مرتبطة بالتحديث.',category:'تحديثات الموقع',date:'2026',status:'خبر تجريبي',details:['ما الجديد في التحديث','التغييرات التي تمت','طريقة استخدام الميزة','ملاحظات وروابط مرتبطة']},
};

export const ExploreDetailPage:React.FC=()=>{
  const{type,id}=useParams();
  const nav=useNavigate();
  const item=details[`${type}/${id}`];
  if(!item)return <div className="min-h-screen bg-[#080808] px-5 pt-32 text-center" dir="rtl"><h1 className="text-3xl font-black">العنصر غير متاح</h1><button onClick={()=>nav(-1)} className="mt-6 inline-flex items-center gap-2 rounded-xl border border-white/10 bg-[#111] px-5 py-3 text-sm font-bold"><ArrowRight className="h-4 w-4"/>الرجوع</button></div>;
  const Icon=item.type==='work'?Briefcase:Newspaper;
  return <div className="min-h-screen bg-[#080808] px-5 pb-24 pt-32" dir="rtl"><div className="mx-auto max-w-5xl"><button onClick={()=>nav(-1)} className="mb-8 inline-flex items-center gap-2 rounded-xl border border-white/10 bg-[#111] px-4 py-2.5 text-sm font-bold transition hover:border-[#D51F2B]/60"><ArrowRight className="h-4 w-4 text-[#D51F2B]"/>الرجوع</button><div className="overflow-hidden rounded-3xl border border-white/10 bg-[#101010]"><div className="grid min-h-72 place-items-center bg-[#080808]"><div className="grid h-24 w-24 place-items-center rounded-3xl border border-[#D51F2B]/30 bg-[#D51F2B]/10"><Icon className="h-10 w-10 text-[#D51F2B]"/></div></div><div className="p-7 sm:p-10"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#D51F2B]/10 px-3 py-1 text-xs font-black text-[#D51F2B]">{item.type==='work'?'أعمال سعيد':'أخبار سعيد'}</span><span className="rounded-full border border-white/10 bg-[#151515] px-3 py-1 text-xs text-gray-400">{item.status}</span></div><h1 className="mt-4 text-3xl font-black sm:text-5xl">{item.title}</h1><p className="mt-5 max-w-3xl text-sm leading-8 text-gray-300 sm:text-base">{item.description}</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-white/10 bg-[#0b0b0b] p-4"><Tag className="mb-2 h-4 w-4 text-[#D51F2B]"/><div className="text-[11px] text-gray-500">التصنيف</div><div className="mt-1 text-sm font-bold">{item.category}</div></div><div className="rounded-xl border border-white/10 bg-[#0b0b0b] p-4"><Calendar className="mb-2 h-4 w-4 text-[#D51F2B]"/><div className="text-[11px] text-gray-500">التاريخ</div><div className="mt-1 text-sm font-bold">{item.date}</div></div><div className="rounded-xl border border-white/10 bg-[#0b0b0b] p-4"><FileText className="mb-2 h-4 w-4 text-[#D51F2B]"/><div className="text-[11px] text-gray-500">النوع</div><div className="mt-1 text-sm font-bold">{item.type==='work'?'عمل / مشروع':'خبر'}</div></div></div><div className="mt-8 rounded-2xl border border-white/10 bg-[#0b0b0b] p-5 sm:p-6"><h2 className="text-lg font-black">التفاصيل الكاملة</h2><p className="mt-3 text-sm leading-8 text-gray-400">{item.overview}</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{item.details.map((x,i)=><div key={i} className="flex items-start gap-3 rounded-xl border border-white/10 bg-[#111] p-4 text-sm text-gray-300"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#D51F2B]"/><span>{x}</span></div>)}</div><div className="mt-8 rounded-2xl border border-dashed border-white/10 bg-[#090909] p-6 text-center text-sm text-gray-500">هنا تظهر الصور والمقاطع والروابط والملفات الخاصة بالعنصر عند إضافتها.</div></div></div></div></div>;
};