import React from 'react';
import {ArrowRight,Briefcase,Gamepad2,BookOpen,Music2,Camera,FileText} from 'lucide-react';
import {useLocation,useNavigate,useParams} from 'react-router-dom';

type ItemDetail={title:string;type:string;description:string;overview:string;details:string[]};
const items:Record<string,ItemDetail>={
'مشروع|ARDR':{title:'ARDR',type:'مشروع',description:'مجموعة ومشروع رقمي يضم عدداً من الأقسام والخدمات والمنصات تحت هوية ARDR.',overview:'ARDR مشروع يتم تطويره كمنظومة رقمية متكاملة، بحيث يكون لكل قسم تخصصه وتجربته الخاصة مع ربط الخدمات والحسابات داخل منظومة واحدة.',details:['الحالة: قيد التطوير والتوسع','النوع: مشروع ومنظومة رقمية','يشمل أقساماً وخدمات رقمية متعددة','يعتمد على هويات وتجارب مستقلة لكل قسم']},
'مشروع|سعيد فريم':{title:'سعيد فريم',type:'مشروع',description:'مشروع سعيد للتصوير والتغطيات الإعلامية.',overview:'سعيد فريم مخصص لأعمال التصوير والتغطيات للفعاليات والمناسبات والمنتجات، مع تقديم المحتوى بصورة احترافية تناسب الجهة أو العميل.',details:['التخصص: تصوير وتغطيات','نوع المشروع: إعلامي','يشمل تغطيات فعاليات ومنتجات ومناسبات']},
'مشروع|مشروع جديد':{title:'مشروع جديد',type:'مشروع',description:'مساحة مخصصة لعرض أحد مشاريع سعيد القادمة.',overview:'هذه الصفحة مهيأة لعرض المشروع القادم عند اعتماده، وتشمل الوصف والحالة والتاريخ والتفاصيل والروابط المرتبطة به.',details:['الحالة: قريباً','التفاصيل ستضاف عند اعتماد المشروع']},
'إعلام|الملف الإعلامي للشركات':{title:'الملف الإعلامي للشركات',type:'إعلام',description:'ملف مخصص للشركات والجهات التي تحتاج معلومات سعيد الرسمية.',overview:'يجمع هذا القسم النبذة الرسمية وبيانات التواصل والمواد التي تحتاجها الشركات والجهات للتعاون أو التغطية الإعلامية.',details:['نبذة رسمية','بيانات تواصل الأعمال','مواد مخصصة للجهات والشركات']},
'إعلام|الهوية الإعلامية':{title:'الهوية الإعلامية',type:'إعلام',description:'مواد وهوية سعيد للاستخدام الإعلامي.',overview:'صفحة مخصصة للمواد الرسمية التي يمكن استخدامها في التغطيات أو التعاون الإعلامي.',details:['مواد وهوية رسمية','روابط وملفات إعلامية','استخدام مخصص للجهات']},
'إعلام|بيانات سعيد':{title:'بيانات سعيد',type:'إعلام',description:'معلومات مختصرة ورسمية عن سعيد.',overview:'تعرض الصفحة بيانات سعيد المختصرة والجاهزة للاستخدام من الجهات والشركات ووسائل الإعلام.',details:['معلومات مختصرة','بيانات رسمية','مخصصة للتعاون الإعلامي']},
'لعبة|Rise of Kingdoms':{title:'Rise of Kingdoms',type:'لعبة',description:'صفحة اللعبة ومحتوى سعيد المرتبط بها.',overview:'تجمع هذه الصفحة بيانات اللعبة والمحتوى الذي يقدمه سعيد عنها والمقاطع أو الأنشطة المرتبطة بها.',details:['التصنيف: ألعاب','تظهر المقاطع والمحتوى المرتبط باللعبة هنا']},
'لعبة|لعبة تجريبية':{title:'لعبة تجريبية',type:'لعبة',description:'نموذج لعرض الألعاب داخل سعيد اكسترا.',overview:'صفحة مستقلة تعرض بيانات اللعبة والمنصة والمحتوى والمقاطع المرتبطة بها.',details:['البيانات تجريبية حالياً']},
'لعبة|لعبة تجريبية 2':{title:'لعبة تجريبية 2',type:'لعبة',description:'نموذج إضافي لعرض الألعاب.',overview:'صفحة مستقلة للعبة ومحتواها المرتبط بسعيد اكسترا.',details:['البيانات تجريبية حالياً']},
'قصة|قصة تجريبية':{title:'قصة تجريبية',type:'قصة',description:'صفحة مستقلة لقصة من مكتبة قصص سعيد.',overview:'تعرض الصفحة غلاف القصة ووصفها وتصنيفها وتاريخ نشرها والمحتوى المرتبط بها.',details:['التصنيف: قصة','المحتوى تجريبي حالياً']},
'قصة|قصة تجريبية 2':{title:'قصة تجريبية 2',type:'قصة',description:'صفحة مستقلة لقصة من مكتبة سعيد.',overview:'تعرض الصفحة تفاصيل القصة والمحتوى المرتبط بها.',details:['المحتوى تجريبي حالياً']},
'قصة|قصة تجريبية 3':{title:'قصة تجريبية 3',type:'قصة',description:'صفحة مستقلة لقصة من مكتبة سعيد.',overview:'تعرض الصفحة تفاصيل القصة والمحتوى المرتبط بها.',details:['المحتوى تجريبي حالياً']},
'شيلة|شيلة تجريبية':{title:'شيلة تجريبية',type:'شيلة',description:'صفحة مستقلة لعمل من سعيد ميوزك.',overview:'تعرض الصفحة بيانات الشيلة وتاريخ الإصدار وروابط الاستماع والمحتوى المرتبط بالعمل.',details:['التصنيف: شيلة','المحتوى تجريبي حالياً']},
'شيلة|شيلة تجريبية 2':{title:'شيلة تجريبية 2',type:'شيلة',description:'صفحة مستقلة لعمل من سعيد ميوزك.',overview:'تعرض الصفحة بيانات العمل وروابطه.',details:['المحتوى تجريبي حالياً']},
'شيلة|شيلة تجريبية 3':{title:'شيلة تجريبية 3',type:'شيلة',description:'صفحة مستقلة لعمل من سعيد ميوزك.',overview:'تعرض الصفحة بيانات العمل وروابطه.',details:['المحتوى تجريبي حالياً']},
'تغطية|تغطية تجريبية':{title:'تغطية تجريبية',type:'تغطية',description:'صفحة مستقلة لتغطية من سعيد فريم.',overview:'تعرض الصفحة الجهة والتاريخ والموقع ونوع التغطية والصور أو المقاطع المرتبطة بها.',details:['التصنيف: تغطية','المحتوى تجريبي حالياً']},
'تغطية|تغطية تجريبية 2':{title:'تغطية تجريبية 2',type:'تغطية',description:'صفحة مستقلة لتغطية من سعيد فريم.',overview:'تعرض الصفحة معلومات وصور التغطية.',details:['المحتوى تجريبي حالياً']},
'تغطية|تغطية تجريبية 3':{title:'تغطية تجريبية 3',type:'تغطية',description:'صفحة مستقلة لتغطية من سعيد فريم.',overview:'تعرض الصفحة معلومات وصور التغطية.',details:['المحتوى تجريبي حالياً']}};
const iconFor=(type:string)=>type==='مشروع'?Briefcase:type==='لعبة'?Gamepad2:type==='قصة'?BookOpen:type==='شيلة'?Music2:type==='تغطية'?Camera:FileText;
export const SaeedItemDetailPage:React.FC=()=>{const{type,title}=useParams();const nav=useNavigate();const location=useLocation();const decodedType=decodeURIComponent(type||'');const decodedTitle=decodeURIComponent(title||'');const item=items[`${decodedType}|${decodedTitle}`];const goBack=()=>{const sourceAnchor=(location.state as any)?.sourceAnchor||sessionStorage.getItem('sba_source_card');if(sourceAnchor)sessionStorage.setItem('sba_return_card',sourceAnchor);nav(-1)};if(!item)return <div className="min-h-screen bg-[#080808] px-5 pt-32 text-center" dir="rtl"><h1 className="text-3xl font-black">العنصر غير متاح</h1><button onClick={goBack} className="mt-6 inline-flex items-center gap-2 rounded-xl border border-white/10 bg-[#111] px-5 py-3 text-sm font-bold"><ArrowRight className="h-4 w-4"/>الرجوع</button></div>;const Icon=iconFor(item.type);return <div className="min-h-screen bg-[#080808] px-5 pb-24 pt-32" dir="rtl"><div className="mx-auto max-w-5xl"><button onClick={goBack} className="mb-8 inline-flex items-center gap-2 rounded-xl border border-white/10 bg-[#111] px-4 py-2.5 text-sm font-bold transition hover:border-[#D51F2B]/60"><ArrowRight className="h-4 w-4 text-[#D51F2B]"/>الرجوع</button><div className="overflow-hidden rounded-3xl border border-white/10 bg-[#101010]"><div className="grid min-h-72 place-items-center bg-[#080808]"><div className="grid h-24 w-24 place-items-center rounded-3xl border border-[#D51F2B]/30 bg-[#D51F2B]/10"><Icon className="h-10 w-10 text-[#D51F2B]"/></div></div><div className="p-7 sm:p-10"><span className="text-xs font-black text-[#D51F2B]">{item.type}</span><h1 className="mt-3 text-3xl font-black sm:text-5xl">{item.title}</h1><p className="mt-5 max-w-3xl text-sm leading-8 text-gray-300 sm:text-base">{item.description}</p><div className="mt-8 rounded-2xl border border-white/10 bg-[#0b0b0b] p-5"><h2 className="text-lg font-black">عن العنصر</h2><p className="mt-3 text-sm leading-8 text-gray-400">{item.overview}</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{item.details.map((x,i)=><div key={i} className="rounded-xl border border-white/10 bg-[#111] p-4 text-sm text-gray-300">{x}</div>)}</div></div></div></div></div>};