import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Bell, CalendarDays } from 'lucide-react';
import { FavoriteButton } from './FavoriteButton';
import { ShareButton } from './ShareButton';
import { SmartPlatformIcon } from './SmartLinkProfileCard';
import { smartLinkPlatforms } from '../lib/smartLinks';
import { downloadEventCalendar } from '../lib/eventCalendar';
import { countdown, eventDate, type SaeedEvent } from '../data/eventsData';
export function EventReminder({ event, isArabic, iconOnly = false }: { event: SaeedEvent; isArabic: boolean; iconOnly?: boolean }) {
  const [message, setMessage] = useState(false);
  return <div><button type="button" onClick={() => { downloadEventCalendar(event, isArabic); setMessage(true); }} title={isArabic ? 'تذكير قبل 15 دقيقة في التقويم' : 'Calendar reminder 15 minutes before'} aria-label={isArabic ? 'ذكرني' : 'Remind me'} className={iconOnly ? 'grid h-9 w-9 place-items-center rounded-full border border-white/10 bg-black/70' : 'flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 bg-[#171717] px-4 py-3 text-xs font-bold'}><Bell className="h-4 w-4 text-[#ED1C2E]"/>{!iconOnly && (isArabic ? 'ذكرني' : 'Remind me')}</button>{message && <p role="status" className="mt-2 max-w-xs rounded-lg bg-[#111] p-2 text-[10px] leading-5 text-gray-300">{isArabic ? 'افتح ملف التقويم المحمّل وأضف الفعالية لتفعيل تذكير قبل 15 دقيقة. التذكير يعتمد على إعدادات تطبيق التقويم.' : 'Open the downloaded calendar file and add the event to enable a reminder 15 minutes before. Alerts depend on calendar settings.'}</p>}</div>;
}
export function EventCard({ event, isArabic, now, library = false }: { event: SaeedEvent; isArabic: boolean; now: number; library?: boolean }) {
  const title = isArabic ? event.title : event.titleEn || event.title, url = `/events/${event.id}`, platform = smartLinkPlatforms.find(p => p.id === event.platform);
  return <article className="flex h-full flex-col overflow-hidden rounded-[26px] border border-white/10 bg-[#111] text-start"><div className="relative"><Link to={url}><img src={event.image} alt={title} loading="lazy" className="aspect-video w-full object-cover"/></Link>{library && <div className="absolute left-3 top-3 flex gap-2"><FavoriteButton id={`event-${event.id}`} title={title} url={url} type={isArabic ? 'فعالية' : 'Event'}/><ShareButton title={title} url={url}/></div>}{event.demo && <span className="absolute bottom-3 right-3 rounded-lg bg-black/80 px-3 py-1 text-[10px] font-bold text-[#ED1C2E]">{isArabic ? 'فعالية تجريبية' : 'Demo event'}</span>}</div><div className="flex flex-1 flex-col p-5"><p aria-live="polite" className="text-xs font-bold text-[#ED1C2E]">{countdown(event, now, isArabic)}</p><h3 className="mt-3 text-xl font-black text-white">{title}</h3><p className="mt-3 text-xs leading-6 text-gray-400">{isArabic ? event.description : event.descriptionEn}</p><p className="mt-4 flex items-center gap-2 text-xs leading-6 text-gray-400"><CalendarDays className="h-4 w-4 shrink-0"/>{eventDate(event, isArabic)}</p><p className="mt-1 text-[10px] text-gray-500">{isArabic ? 'بتوقيت السعودية' : 'Saudi time'}</p><div className="mt-auto pt-5"><div className="flex items-center justify-between gap-3" dir="rtl">{platform ? <span className="order-2 flex items-center gap-2 text-[10px] text-gray-400" title={isArabic ? platform.ar : platform.en}><SmartPlatformIcon platform={platform}/>{isArabic ? platform.ar : platform.en}</span> : <span/>}<Link to={url} className="rounded-xl border border-[#D51F2B]/40 bg-[#D51F2B]/15 px-4 py-3 text-xs font-bold text-white">{isArabic ? library ? 'تفاصيل الفعالية' : 'تفاصيل أكثر' : library ? 'Event details' : 'More details'}</Link></div>{library && <div className="mt-3"><EventReminder event={event} isArabic={isArabic}/></div>}</div></div></article>;
}
