import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Bell, CalendarDays, Clock } from 'lucide-react';
import { FavoriteButton } from './FavoriteButton';
import { ShareButton } from './ShareButton';
import { SmartPlatformIcon } from './SmartLinkProfileCard';
import { smartLinkPlatforms } from '../lib/smartLinks';
import { downloadEventCalendar } from '../lib/eventCalendar';
import { countdown, type SaeedEvent } from '../data/eventsData';
export function EventReminder({ event, isArabic, iconOnly = false }: { event: SaeedEvent; isArabic: boolean; iconOnly?: boolean }) {
 const [message,setMessage]=useState(false);
 return <div><button type="button" onClick={()=>{downloadEventCalendar(event,isArabic);setMessage(true);}} title={isArabic?'تذكير قبل 15 دقيقة في التقويم':'Calendar reminder 15 minutes before'} aria-label={isArabic?'ذكرني':'Remind me'} className={iconOnly?'grid h-9 w-9 place-items-center rounded-full border border-white/10 bg-black/70':'flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 bg-[#171717] px-3 py-2 text-xs font-bold'}><Bell className="h-4 w-4 text-[#ED1C2E]"/>{!iconOnly&&(isArabic?'ذكرني':'Remind me')}</button>{message&&<p role="status" className="mt-2 max-w-xs rounded-lg bg-[#111] p-2 text-[10px] leading-5 text-gray-300">{isArabic?'افتح ملف التقويم المحمّل وأضف الفعالية لتفعيل تذكير قبل 15 دقيقة.':'Open the downloaded calendar file and add the event to enable a reminder 15 minutes before.'}</p>}</div>;
}
export function EventCard({event,isArabic,now,library=false}:{event:SaeedEvent;isArabic:boolean;now:number;library?:boolean}){
 const title=isArabic?event.title:event.titleEn||event.title,url=`/events/${event.id}`,platform=smartLinkPlatforms.find(p=>p.id===event.platform);
 const locale=isArabic?'ar-SA-u-ca-gregory':'en-GB',date=new Date(event.start),zone={timeZone:'Asia/Riyadh'};
 return <article className="flex h-full min-w-0 flex-col overflow-hidden rounded-2xl border border-white/10 bg-[#111] text-start"><div className="relative"><Link to={url}><img src={event.image} alt={title} loading="lazy" className="aspect-[2/1] w-full object-cover"/></Link>{library&&<div className="absolute left-2 top-2 flex gap-1"><FavoriteButton id={`event-${event.id}`} title={title} url={url} type={isArabic?'فعالية':'Event'}/><ShareButton title={title} url={url}/></div>}</div><div className="flex flex-1 flex-col p-3 sm:p-4"><p className="text-[10px] font-bold text-[#ED1C2E]">{countdown(event,now,isArabic)}</p><h3 className="mt-2 text-sm font-black leading-6 sm:text-base">{title}</h3><div className="mt-2 flex flex-wrap gap-1.5 text-[10px] text-gray-300"><span className="flex items-center gap-1 rounded-lg border border-white/10 bg-black/30 px-2 py-1.5"><CalendarDays className="h-3 w-3"/>{new Intl.DateTimeFormat(locale,{...zone,day:'numeric',month:'short',year:'numeric'}).format(date)}</span><span className="flex items-center gap-1 rounded-lg border border-white/10 bg-black/30 px-2 py-1.5"><Clock className="h-3 w-3"/>{new Intl.DateTimeFormat(locale,{...zone,hour:'numeric',minute:'2-digit'}).format(date)}</span></div><p className="mt-2 line-clamp-2 text-[11px] leading-5 text-gray-400">{isArabic?event.description:event.descriptionEn}</p><div className="mt-auto pt-3"><div className="flex items-center justify-start gap-2" dir="ltr"><Link to={url} className="flex h-9 items-center rounded-lg border border-[#D51F2B]/40 bg-[#D51F2B]/15 px-2.5 text-[10px] font-bold text-white">{isArabic?library?'تفاصيل الفعالية':'تفاصيل أكثر':library?'Event details':'More details'}</Link>{platform&&<span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg border border-white/10 bg-black/30" title={isArabic?platform.ar:platform.en} aria-label={isArabic?platform.ar:platform.en}><SmartPlatformIcon platform={platform}/></span>}</div>{library&&<div className="mt-2"><EventReminder event={event} isArabic={isArabic}/></div>}</div></div></article>;
}
