import React, { useEffect, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Menu, X, Send, Languages, Search, Bell, Heart } from 'lucide-react';
import { useCMS } from '../context/CMSContext';
import { useLanguage } from '../context/LanguageContext';

const navEnglish:Record<string,string>={'الرئيسية':'Home','مجالات المحتوى':'Content','مجالات العمل':'Work Fields','خدمات سعيد':'Services','أخبار سعيد':'News','أعمال سعيد':'Portfolio','أدوات سعيد':'Resources','عن سعيد':'About','بلوق سعيد':'Blog','تواصل معنا':'Contact'};
export const Navbar: React.FC = () => {
 const {data}=useCMS();const{language,toggleLanguage,isArabic}=useLanguage();const[scrolled,setScrolled]=useState(false);const[mobileMenuOpen,setMobileMenuOpen]=useState(false);const location=useLocation();const links=[...(data.navbar.links||[])].filter(link=>link.isEnabled).sort((a,b)=>a.order-b.order);const label=(text:string)=>language==='en'?(navEnglish[text]||text):text;
 useEffect(()=>{const handleScroll=()=>setScrolled(window.scrollY>40);window.addEventListener('scroll',handleScroll);return()=>window.removeEventListener('scroll',handleScroll)},[]);useEffect(()=>{document.body.style.overflow=mobileMenuOpen?'hidden':'';return()=>{document.body.style.overflow=''}},[mobileMenuOpen]);
 const renderLink=(link:any,mobile=false)=>{const cls=mobile?'py-4 text-base font-bold border-b border-white/5 text-white':`hover:text-[#D51F2B] transition-colors ${location.pathname===link.url?'text-[#D51F2B] font-bold':''}`;const click=mobile?()=>setMobileMenuOpen(false):undefined;const text=label(link.label);if(link.url?.startsWith('/#')||link.url?.startsWith('http'))return <a key={link.id} href={link.url} onClick={click} target={link.isExternal?'_blank':undefined} rel={link.isExternal?'noreferrer':undefined} className={cls}>{text}</a>;return <Link key={link.id} to={link.url||'/'} onClick={click} className={cls}>{text}</Link>};
 const languageButton=<button type="button" onClick={toggleLanguage} className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-[#111] px-3 py-2.5 text-xs font-bold text-white hover:border-[#D51F2B] transition"><Languages className="h-4 w-4"/><span className="hidden xl:inline">{isArabic?'الإنجليزية':'العربية'}</span></button>;
 const utilities=<div className="flex items-center gap-1"><Link to="/saeed/search" className="rounded-xl p-2.5 text-gray-300 transition hover:bg-white/5 hover:text-white" title={isArabic?'البحث الشامل':'Search'} aria-label={isArabic?'البحث الشامل':'Search'}><Search className="h-5 w-5"/></Link><Link to="/saeed/favorites" className="rounded-xl p-2.5 text-gray-300 transition hover:bg-white/5 hover:text-white" title={isArabic?'المفضلة':'Favorites'} aria-label={isArabic?'المفضلة':'Favorites'}><Heart className="h-5 w-5"/></Link><Link to="/saeed/whatsnew" className="relative rounded-xl p-2.5 text-gray-300 transition hover:bg-white/5 hover:text-white" title={isArabic?'ما الجديد؟':'What’s New'} aria-label={isArabic?'ما الجديد؟':'What’s New'}><Bell className="h-5 w-5"/><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-[#D51F2B]"/></Link></div>;
 return <><header className={`fixed top-0 left-0 right-0 z-[100] transition-all duration-300 ${scrolled?'bg-[#080808]/95 backdrop-blur-md border-b border-white/10 py-2.5 shadow-lg':'bg-[#050505]/90 lg:bg-transparent backdrop-blur-md lg:backdrop-blur-none py-3 lg:py-4'}`}><div className="max-w-7xl mx-auto px-5 sm:px-6 lg:px-8 flex items-center justify-between gap-3"><Link to="/" className="flex items-center group py-1 shrink-0"><img src={data.global.logoUrl||'/assets/sba_logo_transparent.png'} alt={data.global.websiteName} className="h-11 sm:h-14 md:h-16 w-auto object-contain group-hover:scale-105 transition-transform"/></Link><nav className="hidden lg:flex items-center justify-center gap-4 xl:gap-6 text-sm font-medium text-gray-300 flex-1 min-w-0">{links.map(link=>renderLink(link))}</nav><div className="hidden lg:flex items-center gap-2 shrink-0">{utilities}{languageButton}<Link to={data.navbar.contactBtnUrl||'/contact'} className="sba-btn-primary px-5 py-2.5 text-xs flex items-center gap-2"><Send className="w-3.5 h-3.5"/><span>{language==='en'?'Contact':(data.navbar.contactBtnLabel||'تواصل معنا')}</span></Link></div><div className="lg:hidden flex items-center gap-1">{utilities}{languageButton}<button type="button" onClick={()=>setMobileMenuOpen(true)} className="p-2 text-white hover:text-[#D51F2B]" aria-label={isArabic?'فتح القائمة':'Open menu'}><Menu className="w-7 h-7"/></button></div></div></header>{mobileMenuOpen&&<div className="lg:hidden fixed inset-0 z-[9999] bg-[#050505]" dir={isArabic?'rtl':'ltr'}><div className="h-[76px] px-5 flex items-center justify-between border-b border-white/10 bg-[#080808]"><img src={data.global.logoUrl||'/assets/sba_logo_transparent.png'} alt={data.global.websiteName} className="h-11 w-auto object-contain"/><button type="button" onClick={()=>setMobileMenuOpen(false)} className="p-2 text-white"><X className="w-8 h-8"/></button></div><div className="h-[calc(100dvh-76px)] overflow-y-auto px-6 py-4"><nav className="flex flex-col">{links.map(link=>renderLink(link,true))}</nav><Link to={data.navbar.contactBtnUrl||'/contact'} onClick={()=>setMobileMenuOpen(false)} className="sba-btn-primary w-full py-4 text-center block text-sm font-bold mt-6">{language==='en'?'Contact':(data.navbar.contactBtnLabel||'تواصل معنا')}</Link></div></div>}</>;
};
