import React from'react';
import{Link}from'react-router-dom';
import{Briefcase,ChevronLeft,ExternalLink}from'lucide-react';

import{useLanguage}from'../context/LanguageContext';
import{FavoriteButton}from'./FavoriteButton';
import{ShareButton}from'./ShareButton';
import{ardrServiceWork}from'../data/worksData';

export const PortfolioSection:React.FC=()=>{const{isArabic}=useLanguage();const work=ardrServiceWork;const url=`/work/${work.slug}`;return <section id="portfolio-section" className="relative border-t border-white/5 bg-[#080808] py-24" dir={isArabic?'rtl':'ltr'}><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-10 text-center"><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-white/10 bg-[#191919] px-4 py-1.5 text-xs font-semibold text-[#D51F2B]"><Briefcase className="h-3.5 w-3.5"/><span>{isArabic?'معرض الأعمال':'Portfolio'}</span></div><h2 className="text-3xl font-black tracking-tight text-white sm:text-5xl">{isArabic?'أعمال سعيد':'Saeed Works'}</h2><p className="mx-auto mt-4 max-w-2xl text-base font-light leading-relaxed text-[#B8B8B8] sm:text-lg">{isArabic?'أعمال ومشاريع سعيد الرقمية.':'Saeed’s digital work and projects.'}</p></div><div className="mx-auto max-w-3xl"><article className="sba-card relative overflow-hidden p-5 sm:p-6"><FavoriteButton id="work-ardr-service" title={work.title} url={url} type={isArabic?'عمل':'Work'} className="absolute left-4 top-4 z-10"/><ShareButton title={work.title} url={url} className="absolute left-14 top-4 z-10"/><div className="mb-5 overflow-hidden rounded-2xl border border-[#6D28D9]/35 bg-[#0C0A12]"><img src={work.bannerUrl} alt="ARDR Service" className="aspect-[2/1] w-full object-contain" loading="lazy"/></div><div className="mb-3 flex items-center gap-3"><img src={work.logoUrl} alt="ARDR Service" className="h-12 w-12 shrink-0 object-contain" loading="lazy"/><h3 className="text-xl font-black text-white">ARDR Service</h3></div><p className="mt-2 text-sm leading-7 text-[#B8B8B8]">{isArabic?work.shortDescription:work.shortDescriptionEn}</p><div className="mt-6 grid gap-3 border-t border-white/5 pt-5 sm:grid-cols-2"><a href={work.previewUrl} target="_blank" rel="noopener noreferrer" className="flex items-center justify-center gap-2 rounded-xl border border-[#D51F2B]/40 bg-[#D51F2B]/15 px-5 py-3 text-xs font-black text-white hover:bg-[#D51F2B]/25"><ExternalLink className="h-4 w-4 text-[#D51F2B]"/>{isArabic?'معاينة العمل':'Preview Work'}</a><Link to={url} className="flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-[#191919] px-5 py-3 text-xs font-black text-white hover:border-[#D51F2B]">{isArabic?'استكشاف':'Explore'}<ChevronLeft className="h-4 w-4 text-[#D51F2B]"/></Link></div></article></div></div></section>};
