import React,{useEffect,useState}from'react';
import{Bell,Clock3,Download,ExternalLink}from'lucide-react';
import{FavoriteButton}from'./FavoriteButton';

export type MetricItem={id:string;label:string;value:number;suffix?:string;enabled:boolean;order:number};
export type ScheduleItem={id:string;kind:'video'|'live';title:string;description:string;bannerUrl?:string;date:string;time:string;countdown:string;url?:string;enabled:boolean;order:number};
export type LaunchItem={id:string;title:string;label:string;bannerUrl?:string;days:string;hours:string;minutes:string;seconds:string;enabled:boolean;order:number};
export type WallpaperItem={id:string;title:string;device:string;imageUrl?:string;downloadUrl?:string;enabled:boolean;order:number};
export type ArchiveItem={id:string;title:string;year:string;status:string;description:string;url?:string;enabled:boolean;order:number};
export type PollOption={id:string;label:string;imageUrl?:string};
export type PollData={title:string;description:string;typeLabel:string;options:PollOption[]};
export type SpecialModules={numbers:MetricItem[];analytics:MetricItem[];schedule:ScheduleItem[];launches:LaunchItem[];wallpapers:WallpaperItem[];archive:ArchiveItem[];poll:PollData};
export const defaultSpecialModules:SpecialModules={numbers:[{id:'works',label:'عمل ومشروع',value:28,suffix:'+',enabled:true,order:1},{id:'experience',label:'سنة خبرة',value:5,suffix:'+',enabled:true,order:2},{id:'coverage',label:'تغطية',value:42,suffix:'+',enabled:true,order:3},{id:'content',label:'محتوى منشور',value:190,suffix:'+',enabled:true,order:4}],analytics:[{id:'visits',label:'زيارة',value:18420,suffix:'+',enabled:true,order:1},{id:'views',label:'صفحة مشاهدة',value:46300,suffix:'+',enabled:true,order:2},{id:'engagement',label:'متوسط التفاعل',value:68,suffix:'%',enabled:true,order:3},{id:'requests',label:'طلبات',value:320,suffix:'+',enabled:true,order:4}],schedule:[{id:'video-1',kind:'video',title:'اسم المقطع القادم',description:'وصف مختصر للمقطع القادم يظهر هنا.',bannerUrl:'',date:'12/09/2026',time:'9:00 PM',countdown:'02 : 14 : 35',url:'',enabled:true,order:1},{id:'live-1',kind:'live',title:'اسم البث القادم',description:'وصف مختصر للبث القادم يظهر هنا.',bannerUrl:'',date:'12/09/2026',time:'9:00 PM',countdown:'02 : 14 : 35',url:'',enabled:true,order:2}],launches:[{id:'launch-1',title:'مشروع جديد',label:'الإطلاق القادم',bannerUrl:'',days:'12',hours:'08',minutes:'44',seconds:'19',enabled:true,order:1}],wallpapers:['iOS','Android','Laptop','PC'].map((device,i)=>({id:`wallpaper-${i+1}`,title:`خلفية سعيد ${device}`,device,imageUrl:'',downloadUrl:'',enabled:true,order:i+1})),archive:[{id:'archive-1',title:'ARDR',year:'2026',status:'مستمر',description:'كل بيانات العمل وحالته وروابطه تظهر هنا.',enabled:true,order:1},{id:'archive-2',title:'سعيد فريم',year:'2026',status:'مستمر',description:'كل بيانات العمل وحالته وروابطه تظهر هنا.',enabled:true,order:2},{id:'archive-3',title:'عمل سابق',year:'2025',status:'مكتمل',description:'كل بيانات العمل وحالته وروابطه تظهر هنا.',enabled:true,order:3}],poll:{title:'وش تختار؟',description:'التصويت يقدر يكون صور، أسماء، أفكار، مقاطع أو أي خيارين وأكثر.',typeLabel:'نوع التصويت: مرن',options:[{id:'a',label:'الخيار الأول'},{id:'b',label:'الخيار الثاني'}]}};
const Counter=({to,suffix=''}:{to:number;suffix?:string})=>{const[v,setV]=useState(0);useEffect(()=>{let f=0;const t=setInterval(()=>{f++;setV(Math.round(to*f/40));if(f>=40)clearInterval(t)},30);return()=>clearInterval(t)},[to]);return <>{v.toLocaleString('en-US')}{suffix}</>};
export const SaeedSpecialModule:React.FC<{id:string;modules?:Partial<SpecialModules>}>=({id,modules})=>{const m={...defaultSpecialModules,...(modules||{})} as SpecialModules;if(id==='numbers'||id==='analytics'){const arr=[...(id==='numbers'?m.numbers:m.analytics)].filter(x=>x.enabled).sort((a,b)=>a.order-b.order);return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{arr.map(x=><div key={x.id} className="rounded-2xl border border-white/10 bg-[#111] p-6 text-center"><div className="text-4xl font-black"><Counter to={Number(x.value)||0} suffix={x.suffix||''}/></div><div className="mt-2 text-sm text-gray-500">{x.label}</div></div>)}</div>}
if(id==='schedule')return <Schedule items={m.schedule}/>;
if(id==='countdown')return <Launches items={m.launches}/>;
if(id==='wallpapers')return <Wallpapers items={m.wallpapers}/>;
if(id==='archive')return <Archive items={m.archive}/>;
if(id==='polls')return <Poll data={m.poll}/>;
return null};
const Schedule=({items}:{items:ScheduleItem[]})=>{const[kind,setKind]=useState<'video'|'live'>('video');const[rem,setRem]=useState<string|null>(null);const shown=items.filter(x=>x.enabled&&x.kind===kind).sort((a,b)=>a.order-b.order);return <div><div className="mb-6 flex justify-center gap-2"><button onClick={()=>setKind('video')} className={`rounded-xl px-5 py-2 ${kind==='video'?'bg-[#B5121B]':'bg-[#111]'}`}>المقاطع</button><button onClick={()=>setKind('live')} className={`rounded-xl px-5 py-2 ${kind==='live'?'bg-[#B5121B]':'bg-[#111]'}`}>البثوث</button></div><div className="space-y-4">{shown.map(x=><div key={x.id} className="mx-auto max-w-4xl overflow-hidden rounded-2xl border border-white/10 bg-[#111]">{x.bannerUrl?<img src={x.bannerUrl} alt={x.title} className="aspect-[21/7] w-full object-cover"/>:<div className="relative aspect-[21/7] w-full bg-[#080808]"><div className="absolute inset-0 grid place-items-center text-sm text-gray-700">بنر المقطع أو البث</div></div>}<div className="p-6"><h3 className="text-xl font-black">{x.title}</h3><p className="mt-2 text-sm text-gray-500">{x.description}</p><div className="mt-4 text-sm">التاريخ: {x.date} · الساعة: {x.time}</div>{x.countdown&&<div className="mt-3 font-black"><Clock3 className="ml-2 inline h-4 w-4 text-[#D51F2B]"/>{x.countdown}</div>}<div className="mt-5 flex flex-wrap gap-2">{x.url&&<a href={x.url} className="inline-flex items-center gap-1 rounded-lg border border-white/15 px-4 py-2 text-xs">الرابط <ExternalLink className="h-3 w-3"/></a>}<button onClick={()=>setRem(rem===x.id?null:x.id)} className="inline-flex items-center gap-1 rounded-lg bg-[#B5121B] px-4 py-2 text-xs"><Bell className="h-3 w-3"/>{rem===x.id?'تم التذكير':'تذكير'}</button></div></div></div>)}</div></div>};
const Launches=({items}:{items:LaunchItem[]})=><div className="space-y-4">{items.filter(x=>x.enabled).sort((a,b)=>a.order-b.order).map(x=><div key={x.id} className="mx-auto max-w-4xl overflow-hidden rounded-3xl border border-white/10 bg-[#111]">{x.bannerUrl?<img src={x.bannerUrl} alt={x.title} className="aspect-[21/7] w-full object-cover"/>:<div className="aspect-[21/7] w-full bg-[#080808] grid place-items-center text-gray-700">بنر المشروع</div>}<div className="p-6 text-center"><div className="text-[#D51F2B]">{x.label}</div><h3 className="mt-2 text-2xl font-black">{x.title}</h3><div className="mx-auto mt-6 grid max-w-xl grid-cols-4 gap-2">{[[x.days,'يوم'],[x.hours,'ساعة'],[x.minutes,'دقيقة'],[x.seconds,'ثانية']].map(([n,l])=><div className="rounded-xl bg-black p-3 text-center" key={l}><div className="text-xl font-black">{n}</div><div className="text-[10px] text-gray-500">{l}</div></div>)}</div></div></div>)}</div>;
const Wallpapers=({items}:{items:WallpaperItem[]})=><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{items.filter(x=>x.enabled).sort((a,b)=>a.order-b.order).map(x=><div key={x.id} className="relative rounded-2xl border border-white/10 bg-[#111] p-3"><FavoriteButton id={x.id} title={x.title} url="/#saeed-wallpapers" type="خلفية" className="absolute left-5 top-5 z-10"/>{x.imageUrl?<img src={x.imageUrl} alt={x.title} className="aspect-[4/3] w-full rounded-xl object-cover"/>:<div className="aspect-[4/3] grid place-items-center rounded-xl bg-[#18090a] text-2xl font-black">SBA</div>}<div className="mt-3 flex items-center justify-between"><span className="rounded-full bg-white/5 px-3 py-1 text-xs">{x.device}</span>{x.downloadUrl&&<a href={x.downloadUrl} className="text-xs"><Download className="inline h-3 w-3"/> تحميل</a>}</div></div>)}</div>;
const Archive=({items}:{items:ArchiveItem[]})=><div className="mx-auto max-w-4xl space-y-4 border-r border-[#B5121B]/40 pr-6">{items.filter(x=>x.enabled).sort((a,b)=>a.order-b.order).map(x=><div key={x.id} className="rounded-2xl border border-white/10 bg-[#111] p-5"><div className="flex justify-between"><b>{x.title}</b><span className="text-xs text-gray-400">{x.status}</span></div><div className="mt-2 text-sm text-gray-500">تاريخ البداية: {x.year}</div><p className="mt-2 text-xs text-gray-600">{x.description}</p>{x.url&&<a href={x.url} className="mt-3 inline-flex text-xs font-bold text-[#D51F2B]">عرض التفاصيل</a>}</div>)}</div>;
const Poll=({data}:{data:PollData})=>{const[v,setV]=useState<string|null>(null);const options=data.options||[];return <div className="mx-auto max-w-3xl rounded-2xl border border-white/10 bg-[#111] p-6"><div className="mb-2 text-center text-xs font-bold text-[#D51F2B]">{data.typeLabel}</div><h3 className="text-center text-xl font-black">{data.title}</h3><p className="mt-2 text-center text-sm text-gray-500">{data.description}</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{options.map((o,i)=>{const pct=v? (v===o.id?64:Math.max(0,36/(Math.max(1,options.length-1)))) : Math.round(100/Math.max(1,options.length));return <button key={o.id} onClick={()=>setV(o.id)} className="overflow-hidden rounded-xl border border-white/10 text-right hover:border-[#D51F2B]">{o.imageUrl?<img src={o.imageUrl} alt={o.label} className="aspect-video w-full object-cover"/>:<div className="aspect-video bg-[#101010] grid place-items-center text-gray-500">صورة اختيارية</div>}<div className="p-3"><div className="font-bold">{o.label}</div><div className="mt-1 text-sm text-gray-500">{Math.round(pct)}%</div></div></button>})}</div></div>};