import {Link} from 'react-router-dom';
import {ExternalLink} from 'lucide-react';
import {useCMS} from '../context/CMSContext';
import {useLanguage} from '../context/LanguageContext';
import {getAds,safeAdUrl,type SaeedAd} from '../data/adsData';
export function SaeedAdCard({ad}:{ad:SaeedAd}){const{isArabic}=useLanguage();return <article className="overflow-hidden rounded-3xl border border-white/10 bg-[#111]">
 <Link to={`/ads/${ad.id}`} aria-label={isArabic?`تفاصيل ${ad.name}`:`About ${ad.nameEn}`}><img src={safeAdUrl(ad.banner)||ad.banner.startsWith('/')&&ad.banner||undefined} alt={isArabic?ad.name:ad.nameEn} className="aspect-[3/1] w-full object-cover" loading="lazy"/></Link>
 <div className="p-5 sm:p-7"><div className="flex items-center gap-4"><img src={safeAdUrl(ad.logo)||ad.logo.startsWith('/')&&ad.logo||undefined} alt="" className="h-16 w-16 shrink-0 rounded-xl object-contain" loading="lazy"/><h3 className="text-xl font-black text-white">{isArabic?ad.name:ad.nameEn}</h3></div><p className="mt-4 line-clamp-3 text-sm leading-7 text-gray-400">{isArabic?ad.description:ad.descriptionEn}</p><div className="mt-6 flex flex-wrap gap-3"><Link to={`/ads/${ad.id}`} className="rounded-xl bg-[#D51F2B] px-5 py-2.5 text-sm font-bold text-white">{isArabic?'تفاصيل الإعلان':'Ad details'}</Link><a href={safeAdUrl(ad.website)} target="_blank" rel="noopener noreferrer sponsored" className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-5 py-2.5 text-sm font-bold text-white">{isArabic?'زيارة الموقع':'Visit website'}<ExternalLink className="h-4 w-4"/></a></div></div></article>;}
export function SaeedAdsSection(){const{data}=useCMS(),{isArabic}=useLanguage();const ads=getAds(data.global).filter(ad=>ad.inSection);if(!ads.length)return null;return <section id="saeed-ads-section" className="border-t border-white/5 bg-[#0B0B0B] py-20" dir={isArabic?'rtl':'ltr'}><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-9 text-center"><p className="mb-2 text-xs font-bold text-[#D51F2B]">{isArabic?'مساحة إعلانية':'Advertising space'}</p><h2 className="text-3xl font-black text-white sm:text-5xl">{isArabic?'سعيد ادز':'Saeed Ads'}</h2></div><div className="grid gap-5 md:grid-cols-2">{ads.map(ad=><SaeedAdCard key={ad.id} ad={ad}/>)}</div></div></section>;}
