import React,{useEffect}from'react';
import{useLanguage}from'../context/LanguageContext';

const exact:Record<string,string>={
'الرئيسية':'Home','المفضلة':'Favorites','الإشعارات':'Notifications','البحث':'Search','اقتراحات':'Suggestions','النتائج':'Results','ما حصلت نتيجة مطابقة.':'No matching result found.','ابحث عن قسم، شيلة، مشروع أو خدمة...':'Search for a section, sheila, project or service...','اضغط لفتح العنصر.':'Tap to open this item.','كل الأقسام والمقاطع والمشاريع والعناصر اللي حفظتها.':'All sections, videos, projects and items you saved.','ما عندك عناصر في المفضلة إلى الآن.':'You do not have any favorites yet.','آخر التنبيهات والتحديثات الجديدة في موقع سعيد.':'Latest alerts and updates on Saeed’s website.','مرحباً بك في موقع سعيد':'Welcome to Saeed’s Website','تقدر الآن تستخدم البحث والمفضلة والتخصيص من الموقع.':'You can now use search, favorites and personalization across the site.','تحديث جديد':'New Update','تم تطوير سعيد كارد وجدول سعيد والمفضلة والتصويت.':'Saeed Card, Saeed Schedule, Favorites and Polls have been improved.','إشعارات سعيد':'Saeed Notifications','هنا تظهر لك الإضافات والتنبيهات الجديدة مستقبلاً.':'New additions and alerts will appear here in the future.','الآن':'Now','اليوم':'Today',
'أرقام سعيد':'Saeed by the Numbers','الأرقام':'Numbers','سعيد كارد':'Saeed Card','الهوية':'Identity','إعلام سعيد':'Saeed Media','الإعلام':'Media','مشاريع سعيد':'Saeed Projects','المشاريع':'Projects','سعيد اكسترا':'Saeed Extra','الألعاب':'Gaming','قصص سعيد':'Saeed Stories','القصص':'Stories','سعيد ميوزك':'Saeed Music','الشيلات':'Sheilat','سعيد فريم':'Saeed Frame','التغطيات':'Coverage','جدول سعيد':'Saeed Schedule','الجدول':'Schedule','عداد الإطلاق':'Launch Countdown','الإطلاق':'Launch','خلفيات سعيد':'Saeed Wallpapers','الخلفيات':'Wallpapers','أرشيف سعيد':'Saeed Archive','الأرشيف':'Archive','تصويت الجمهور':'Audience Poll','التصويت':'Poll','إحصائيات الموقع':'Website Statistics','الإحصائيات':'Statistics',
'أرقام وإحصائيات مختصرة عن الأعمال والمحتوى والخبرة.':'A concise overview of work, content and experience metrics.','بطاقة سعيد الرقمية الرسمية للحفظ والمشاركة والتحميل.':'Saeed’s official digital card for saving, sharing and downloading.','ملف إعلامي مخصص للشركات والجهات.':'A media profile designed for companies and organizations.','مشاريع سعيد الحالية والسابقة وبياناتها.':'Saeed’s current and previous projects with full information.','الألعاب التي لعبها سعيد مع بياناتها.':'Games played by Saeed with their details.','مكتبة كاملة للقصص.':'A complete stories library.','أعمال سعيد من الشيلات وبيانات كل عمل.':'Saeed’s sheilat and details for each release.','التغطيات التي نفذها سعيد وبياناتها.':'Coverage produced by Saeed with complete details.','مواعيد المقاطع والبثوث القادمة.':'Upcoming videos and live stream schedules.','المشاريع والإطلاقات القادمة.':'Upcoming projects and launches.','خلفيات بصور سعيد لمختلف الأجهزة.':'Saeed wallpapers for different devices.','خط زمني للأعمال والمشاريع.':'A timeline of work and projects.','تصويت مرن على صور أو نصوص أو أفكار أو محتوى مختلف.':'Flexible polls for images, text, ideas or other content.','أرقام متحركة تلخص استخدام الموقع.':'Animated metrics summarizing website usage.',
'الملف الإعلامي للشركات':'Corporate Media Kit','نبذة رسمية، صور، بيانات تواصل ومعلومات إعلامية.':'Official bio, photos, contact details and media information.','الهوية الإعلامية':'Media Identity','مواد وروابط رسمية للاستخدام الإعلامي.':'Official assets and links for media use.','بيانات سعيد':'Saeed Information','معلومات مختصرة جاهزة للجهات والشركات.':'Concise information prepared for organizations and companies.','بيانات المشروع وحالته وتاريخ بدايته.':'Project details, status and start date.','مشروع التصوير والتغطيات.':'Photography and event coverage project.','مشروع جديد':'New Project','مكان للمشاريع القادمة.':'A space for upcoming projects.','لعبة تجريبية':'Demo Game','لعبة تجريبية 2':'Demo Game 2','قصة تجريبية':'Demo Story','قصة تجريبية 2':'Demo Story 2','قصة تجريبية 3':'Demo Story 3','شيلة تجريبية':'Demo Sheila','شيلة تجريبية 2':'Demo Sheila 2','شيلة تجريبية 3':'Demo Sheila 3','تغطية تجريبية':'Demo Coverage','تغطية تجريبية 2':'Demo Coverage 2','تغطية تجريبية 3':'Demo Coverage 3','استكشف':'Explore','تشغيل':'Play','حفظ جهة الاتصال':'Save Contact','تحميل الصورة':'Download Image',
'عمل ومشروع':'Works & Projects','سنة خبرة':'Years of Experience','تغطية':'Coverage','محتوى منشور':'Published Content','زيارة':'Visits','صفحة مشاهدة':'Page Views','متوسط التفاعل':'Average Engagement','طلبات':'Requests','المقاطع':'Videos','البثوث':'Live Streams','التاريخ:':'Date:','الساعة:':'Time:','الرابط':'Link','تذكير':'Remind Me','تم التذكير':'Reminder Set','الإطلاق القادم':'Upcoming Launch','يوم':'Days','ساعة':'Hours','دقيقة':'Minutes','ثانية':'Seconds','تحميل':'Download','تاريخ البداية:':'Start Date:','عرض التفاصيل':'View Details','نوع التصويت: مرن':'Poll Type: Flexible','وش تختار؟':'What do you choose?','التصويت يقدر يكون صور، أسماء، أفكار، مقاطع أو أي خيارين وأكثر.':'The poll can include images, names, ideas, videos or two or more options.','الخيار الأول':'First Option','الخيار الثاني':'Second Option','صورة اختيارية':'Optional Image',
'خدمات سعيد':'Saeed Services','الخدمات والحلول الاحترافية':'Professional Services & Solutions','عرض جميع الخدمات':'View All Services','سعر الخدمة:':'Service Price:','حسب الطلب':'On Request','عرض الخدمة':'View Service','تواصل الآن':'Contact Now','الكل':'All','أدوات سعيد':'Saeed Tools','المكتبة والأدوات الحصرية':'Exclusive Library & Tools','عرض جميع الأدوات':'View All Tools','بحث في أدوات سعيد...':'Search Saeed Tools...','فرز:':'Filter:','أدوات':'Tools','استعرض الأداة الكاملة':'View Full Tool','أخبار سعيد':'Saeed News','المركز الإخباري والتغطيات':'News & Coverage Center','عرض جميع الأخبار':'View All News','قراءة الخبر':'Read News','أعمال سعيد':'Saeed Works','معرض الأعمال':'Portfolio','استكشف العمل':'Explore Work','استكشف أعمالي':'Explore My Work',
'تابع سعيد':'Follow Saeed','تابع جديد سعيد أول بأول':'Follow Saeed’s latest updates','تنبيهات مختارة عن المقاطع والشيلات والمشاريع الجديدة.':'Selected alerts about new videos, sheilat and projects.','بريدك الإلكتروني':'Your email','تم':'Done','متابعة':'Follow',
'فرص التعاون والشراكة':'Collaboration & Partnership Opportunities','لنصنع شيئاً مميزاً معاً':'Let’s Create Something Remarkable Together','إذا كان لديك مشروع أو فكرة أو تعاون، يسعدنا التواصل معك وتحويل الرؤية إلى واقع استثنائي.':'If you have a project, idea or collaboration opportunity, I would be happy to connect and turn the vision into something exceptional.','تواصل معنا':'Contact Us',
'سعيد سنترهلب':'Saeed CenterHelp','مركز المساعدة والدعم الخاص بموقع سعيد، للوصول إلى الأسئلة الشائعة والشروحات وطرق التواصل والدعم الفني.':'Saeed’s help and support center for FAQs, guides, contact options and technical support.','الدخول إلى سعيد سنترهلب':'Open Saeed CenterHelp','بلوق سعيد':'Saeed Blog','مدونتي الشخصية التي أشارك فيها المقالات والتجارب والأفكار والمحتوى المتخصص في المحتوى والأعمال.':'My personal blog where I share articles, experiences, ideas and specialized content about content creation and business.','زيارة بلوق سعيد':'Visit Saeed Blog',
'بطاقة اقتراح':'Suggestion Card','عندك فكرة أو اقتراح يساعدنا في تطوير الموقع أو المحتوى؟ شاركنا اقتراحك.':'Have an idea or suggestion that can help improve the website or content? Share it with us.','الاسم':'Name','البريد الإلكتروني':'Email','الرسالة':'Message','المرفق (اختياري - صورة / فيديو / ملف)':'Attachment (Optional - Image / Video / File)','إرسال اقتراح':'Send Suggestion','جاري إرسال الاقتراح...':'Sending suggestion...','تم إرسال اقتراحك بنجاح!':'Your suggestion was sent successfully!','شكراً لمشاركتك معنا في تطوير الخدمات والمحتوى.':'Thank you for helping us improve the services and content.','إرسال اقتراح آخر':'Send Another Suggestion','بطاقة شكاوي':'Complaint Card','واجهتك مشكلة أو عندك شكوى؟ أرسل التفاصيل وسأراجعها بأقرب وقت.':'Have an issue or complaint? Send the details and it will be reviewed as soon as possible.','قسم الشكوى':'Complaint Category','اختر قسم الشكوى...':'Choose a complaint category...','قسم المحتوى والمرئيات':'Content & Visuals','قسم الخدمات والتطوير':'Services & Development','قسم الأدوات والتنزيلات':'Tools & Downloads','مشكلة تقنية في الموقع':'Website Technical Issue','قسم بلاغات عامة':'General Reports','تقديم شكوى':'Submit Complaint','جاري إرسال الشكوى...':'Submitting complaint...','تم تقديم شكواك بنجاح!':'Your complaint was submitted successfully!','تقديم شكوى أخرى':'Submit Another Complaint',
'التواصل المباشر':'Direct Contact','تواصل مع سعيد بن عايض':'Contact Saeed Bin Ayidh','أرحب باستفساراتك، مقترحات المشاريع، وفرص التعاون والتغطيات.':'I welcome your inquiries, project proposals, collaboration opportunities and coverage requests.','الاسم الكامل':'Full Name','موضوع التواصل / اسم المشروع':'Contact Subject / Project Name','التفاصيل والرسالة':'Details & Message','جاري الإرسال...':'Sending...','إرسال الرسالة':'Send Message','تم إرسال رسالتك بنجاح!':'Your message was sent successfully!','شكراً لتواصلك مع سعيد بن عايض. سيتم مراجعة رسالتك والتواصل معك في أقرب وقت.':'Thank you for contacting Saeed Bin Ayidh. Your message will be reviewed and you will be contacted as soon as possible.','إرسال رسالة أخرى':'Send Another Message',
'عن سعيد بن عايض':'About Saeed Bin Ayidh','رؤية مبتكرة في صناعة المحتوى وتطوير الأعمال':'An Innovative Vision in Content Creation and Business Development','خبرة متميزة في التخطيط وصناعة المحتوى المرئي والصوتي':'Strong experience in planning and producing visual and audio content','استراتيجيات تطوير الأعمال وبناء الواجهات الرقمية الفاخرة':'Business development strategies and premium digital interface creation','تقديم حلول الذكاء الاصطناعي والأتمتة الذكية للمشاريع':'AI and smart automation solutions for projects',
'مركز الدعم والدعم الفني':'Help & Technical Support Center','مركز المساعدة والدعم الخاص بموقع سعيد، للوصول إلى الأسئلة الشائعة والشروحات وطرق التواصل.':'Saeed’s help center for FAQs, guides and contact options.','كيف يمكنني طلب خدمة أو استشارة تطوير أعمال؟':'How can I request a service or business development consultation?','يمكنك التواصل المباشر عبر صفحة التواصل أو حجز موعد استشاري للاتفاق على خطة العمل.':'You can contact us directly through the contact page or arrange a consultation to agree on a work plan.','هل تتوفر خدمات التغطيات الميدانية خارج المنطقة؟':'Are field coverage services available outside the region?','نعم، يتم ترتيب وتنسيق التغطيات للمؤتمرات والفعاليات في مختلف المناطق وفق جداول مسبقة.':'Yes. Conference and event coverage can be arranged across different regions based on a scheduled plan.','كيف يمكنني استخدام وتنزيل أدوات وموارد سعيد؟':'How can I use and download Saeed Tools and Resources?','جميع البرومبت والخلفيات والاختصارات متاحة مجاناً ومباشرة للتنزيل عبر قسم الأدوات والموارد.':'Prompts, wallpapers and shortcuts are available free for direct download through the Tools & Resources section.',
'سياسة الخصوصية':'Privacy Policy','سياسة الخصوصية وحماية البيانات':'Privacy Policy & Data Protection','نلتزم في موقع سعيد بن عايض (www.saeedbinayidh.com) بحماية خصوصيتك وبياناتك الشخصية بأعلى معايير الأمان والتشفير.':'At Saeed Bin Ayidh’s website (www.saeedbinayidh.com), we are committed to protecting your privacy and personal data with strong security standards.','1. جمع البيانات':'1. Data Collection','نجمع فقط البيانات الأساسية اللازمة لتقديم الخدمات والاستشارات والإجابة على الاستفسارات وبطاقات الشكاوى والاقتراحات.':'We only collect the basic information needed to provide services, consultations and respond to inquiries, complaints and suggestions.','2. استخدام المعلومات':'2. Use of Information','تُستخدم معلوماتك فقط لتلبية الطلبات، التواصل، وتحسين تجربة التصفح داخل الموقع.':'Your information is used only to fulfill requests, communicate with you and improve your browsing experience.','3. حماية البيانات والتخزين المحلي':'3. Data Protection & Local Storage','يستخدم الموقع تقنيات التخزين المحلي (LocalStorage) لحفظ تفضيلاتك والمحفوظات بأمان كامل على جهازك.':'The website uses local storage (LocalStorage) to save preferences and saved items on your device.',
'الشروط والأحكام':'Terms & Conditions','أهلاً بك في موقع سعيد بن عايض. استخدامك للموقع والأدوات والخدمات المتاحة يعني موافقتك الكاملة على الشروط التالية:':'Welcome to Saeed Bin Ayidh’s website. By using the website, tools and available services, you agree to the following terms:','1. الملكية الفكرية':'1. Intellectual Property','جميع المحتويات والأدوات والبرومبت والتصاميم والشعارات مملوكة لسعيد بن عايض ومحمية بموجب قوانين الملكية الفكرية.':'All content, tools, prompts, designs and logos are owned by Saeed Bin Ayidh and protected by intellectual property laws.','2. الاستخدام العادل للأدوات':'2. Fair Use of Tools','يُسمح باستخدام الأدوات والخلفيات والاختصارات للأغراض الشخصية والتجارية المشروعة ويُمنع إعادة بيعها كمنتجات مستقلة دون إذن.':'Tools, wallpapers and shortcuts may be used for lawful personal and commercial purposes. Reselling them as standalone products without permission is prohibited.',
'الرجوع':'Back','الرجوع للسابقة':'Back','الرجوع للخدمات':'Back to Services','العنصر غير متاح':'Item Unavailable','الخبر غير متاح':'News item unavailable','العمل غير متاح':'Work unavailable','الخدمة غير متاحة':'Service unavailable','الأداة غير متاحة':'Tool unavailable','التصنيف':'Category','التاريخ':'Date','الحالة':'Status','النوع':'Type','التفاصيل':'Details','التفاصيل الكاملة':'Full Details','عن العنصر':'About This Item','نظرة عامة على المشروع':'Project Overview','التحدي والمشكلة':'Challenge','دوري والمسؤوليات':'My Role & Responsibilities','أبرز ما تم تسليمه وإنجازه':'Key Deliverables','النتائج والأثر':'Results & Impact','تفاصيل المشروع':'Project Details','العميل':'Client','السنة':'Year','مشاريع أعمال أخرى':'More Projects','مشاركة الخبر':'Share News','أخبار ذات صلة':'Related News','مقالات ذات صلة':'Related Articles','وقت القراءة:':'Reading time:','الكاتب:':'Author:','إعجاب':'Like','لم يعجبني':'Dislike','حفظ المقال':'Save Article','تم الحفظ في المحفوظات':'Saved','مشاركة المقال':'Share Article','معرض الصور':'Image Gallery','توفير المعاينة':'Preview','الملفات القابلة للتنزيل':'Downloadable Files','تنزيل الأن ←':'Download Now ←','عرض الفيديو':'Video','صورة المحتوى':'Content Image','معاينة المكبرة':'Expanded Preview','مجالات المحتوى':'Content Fields','عن مجال':'About','أبرز المحطات والأعمال المميزة':'Featured Highlights','أحدث الأخبار في هذا المجال':'Latest News in This Field','لا توجد أخبار حديثة مسجلة بهذا المجال حالياً.':'No recent news is available in this field.','روابط المنصات والتواصل':'Platform & Contact Links',
'صفحات سعيد':'Saeed Pages','الحسابات':'Accounts','القنوات':'Channels','المساعدة':'Help','لا توجد حسابات مفعلة':'No active accounts','لا توجد قنوات مضافة':'No channels added','© 2026 سعيد بن عايض — جميع الحقوق محفوظة.':'© 2026 Saeed Bin Ayidh — All rights reserved.','جميع الحقوق محفوظة.':'All rights reserved.'
};

const phraseRules:[string,string][]=[
['سعيد بن عايض','Saeed Bin Ayidh'],['مجالات العمل','Work Fields'],['مجالات سعيد','Saeed Fields'],['مجالات المحتوى','Content Fields'],['التسويق الرقمي','Digital Marketing'],['تطوير الأعمال','Business Development'],['الذكاء الاصطناعي','Artificial Intelligence'],['بناء الواجهات','Interface Development'],['التغطيات الميدانية','Field Coverage'],['صناعة المحتوى','Content Creation'],['البرومبت','Prompts'],['واجهات الساعات','Watch Faces'],['خلفيات الجوال','Mobile Wallpapers'],['الفلاتر','Filters'],['الاختصارات','Shortcuts'],['صفحة حسابات','Profile Pages'],['بدون صورة','No Image'],['جديد','New'],['مستمر','Ongoing'],['مكتمل','Completed'],['عام','Year'],['مجاناً','for free'],['صورة','Image'],['فيديو','Video'],['ملف','File'],['مشروع','Project'],['خدمة','Service'],['خبر','News'],['عمل','Work'],['أداة','Tool'],['مجال','Field'],['قصة','Story'],['شيلة','Sheila'],['لعبة','Game'],['قسم','Section'],['مقطع','Video'],['بث','Live Stream']
];
const hasArabic=(s:string)=>/[\u0600-\u06FF]/.test(s);
const translate=(value:string)=>{const lead=value.match(/^\s*/)?.[0]||'',trail=value.match(/\s*$/)?.[0]||'',core=value.trim();if(!core||!hasArabic(core))return value;if(exact[core])return lead+exact[core]+trail;let out=core;for(const[a,b]of phraseRules)out=out.split(a).join(b);return lead+out+trail};

const textOriginal=new WeakMap<Text,string>();
const attrOriginal=new WeakMap<Element,Map<string,string>>();
const attrs=['placeholder','aria-label','title','alt'];
const skip=(el:Element|null)=>!el||['SCRIPT','STYLE','NOSCRIPT','CODE','PRE'].includes(el.tagName)||Boolean(el.closest('[data-no-translate="true"]'));

export const SiteTranslationRuntime:React.FC=()=>{const{language}=useLanguage();useEffect(()=>{if(location.pathname.startsWith('/admin'))return;let busy=false;const applyNode=(node:Node)=>{if(node.nodeType===Node.TEXT_NODE){const t=node as Text;const p=t.parentElement;if(skip(p))return;if(!textOriginal.has(t))textOriginal.set(t,t.data);const original=textOriginal.get(t)||t.data;const desired=language==='en'?translate(original):original;if(t.data!==desired)t.data=desired;return}if(node.nodeType!==Node.ELEMENT_NODE)return;const el=node as Element;if(skip(el))return;let map=attrOriginal.get(el);if(!map){map=new Map();attrOriginal.set(el,map)}for(const a of attrs){const v=el.getAttribute(a);if(v&&!map.has(a))map.set(a,v);const original=map.get(a);if(original){const desired=language==='en'?translate(original):original;if(el.getAttribute(a)!==desired)el.setAttribute(a,desired)}}el.childNodes.forEach(applyNode)};const run=()=>{if(busy)return;busy=true;try{document.querySelectorAll('body *').forEach(el=>applyNode(el));document.documentElement.dir=language==='en'?'ltr':'rtl';document.documentElement.lang=language;document.body.setAttribute('dir',language==='en'?'ltr':'rtl')}finally{busy=false}};run();const obs=new MutationObserver(m=>{if(busy)return;busy=true;try{for(const x of m){if(x.type==='characterData')applyNode(x.target);x.addedNodes.forEach(applyNode)}}finally{busy=false}});obs.observe(document.body,{subtree:true,childList:true,characterData:true});const timer=setTimeout(run,80);return()=>{clearTimeout(timer);obs.disconnect()}},[language]);return null};
