import React from 'react';
import { TrendingUp, Briefcase, Cpu, Layout, Camera, Layers } from 'lucide-react';
import { siteData } from '../data/siteData';
import { useLanguage } from '../context/LanguageContext';
import { FavoriteButton } from './FavoriteButton';
const en:Record<string,{title:string;description:string}>={
 'digital-marketing':{title:'Digital Marketing',description:'Campaign planning, marketing content, digital presence and brand growth.'},
 'biz-dev':{title:'Business Development',description:'Developing ideas, projects, strategies, products and services for sustainable growth.'},
 'ai-solutions':{title:'Artificial Intelligence',description:'Using AI tools and solutions to improve business, content and automation.'},
 'ui-ux':{title:'Interface Development',description:'Designing and building modern digital interfaces and experiences for websites and apps.'},
 'coverages':{title:'Event Coverage',description:'Professional coverage of conferences, events and field content.'}
};
export const WorkFieldsSection:React.FC=()=>{const{isArabic}=useLanguage();const getIcon=(name:string)=>name==='TrendingUp'?TrendingUp:name==='Briefcase'?Briefcase:name==='Cpu'?Cpu:name==='Layout'?Layout:Camera;return <section id="work-fields" className="py-24 relative bg-[#080808] border-t border-white/5" dir={isArabic?'rtl':'ltr'}><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center max-w-3xl mx-auto mb-16 space-y-3"><div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-[#191919] border border-white/10 text-xs font-semibold text-[#D51F2B]"><Layers className="w-3.5 h-3.5"/><span>{isArabic?'الخبرات والحلول المتقدمة':'Expertise & Advanced Solutions'}</span></div><h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight">{isArabic?'مجالات العمل':'Work Fields'}</h2><p className="text-base sm:text-lg text-[#B8B8B8] font-light">{isArabic?'حلول واحترافية متكاملة للمشاريع والعلامات التجارية الشريكة.':'Integrated professional solutions for projects and partner brands.'}</p></div><div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 gap-6">{siteData.workFields.map(field=>{const Icon=getIcon(field.iconName);const t=en[field.id];return <div key={field.id} className="sba-card group relative p-6 flex flex-col justify-between items-start"><FavoriteButton id={`work-${field.id}`} title={field.title} url="/#work-fields" type="مجال عمل" className="absolute left-4 top-4"/><div className="w-12 h-12 rounded-xl bg-[#191919] border border-white/10 flex items-center justify-center text-[#D51F2B] mb-6 group-hover:bg-[#B5121B] group-hover:text-white transition-all shadow-md"><Icon className="w-6 h-6 stroke-[1.75]"/></div><div className="space-y-2"><h3 className="text-lg font-bold text-white group-hover:text-[#D51F2B] transition-colors">{isArabic?field.title:(t?.title||field.title)}</h3><p className="text-xs text-[#B8B8B8] leading-relaxed font-light">{isArabic?field.description:(t?.description||field.description)}</p></div></div>})}</div></div></section>};
