import React, { createContext, useContext, useState, useEffect } from 'react';
import { CMSDataStore, loadCMSData, saveCMSData, applyThemeVariables, defaultCMSData, ThemeSettings, GlobalSettings, NavbarSettings, HeroSettings, SectionConfig, SubmissionItem, MediaFile } from '../data/cmsStorage';
import { ContentFieldItem, NewsItem, ToolItem, PortfolioItem, ServiceItem, BlogPostItem } from '../types';

interface CMSContextType {
  data: CMSDataStore; isAuthenticated: boolean; authLoading: boolean; hasUnsavedChanges: boolean; isSaving: boolean; lastSavedAt: Date | null;
  login:(email:string,pass:string)=>Promise<boolean>; logout:()=>Promise<void>; changePassword:(currentPassword:string,newPassword:string)=>Promise<boolean>; saveChanges:()=>Promise<boolean>;
  updateTheme:(theme:Partial<ThemeSettings>)=>void; resetThemeToDefault:()=>void; updateGlobal:(global:Partial<GlobalSettings>)=>void; updateNavbar:(navbar:Partial<NavbarSettings>)=>void; updateHero:(hero:Partial<HeroSettings>)=>void; updateSections:(sections:SectionConfig[])=>void;
  addContentField:(item:ContentFieldItem)=>void; updateContentField:(id:string,item:Partial<ContentFieldItem>)=>void; deleteContentField:(id:string)=>void;
  addNews:(item:NewsItem)=>void; updateNews:(id:string,item:Partial<NewsItem>)=>void; deleteNews:(id:string)=>void;
  addBlog:(item:BlogPostItem)=>void; updateBlog:(id:string,item:Partial<BlogPostItem>)=>void; deleteBlog:(id:string)=>void;
  addTool:(item:ToolItem)=>void; updateTool:(id:string,item:Partial<ToolItem>)=>void; deleteTool:(id:string)=>void;
  addService:(item:ServiceItem)=>void; updateService:(id:string,item:Partial<ServiceItem>)=>void; deleteService:(id:string)=>void;
  addPortfolio:(item:PortfolioItem)=>void; updatePortfolio:(id:string,item:Partial<PortfolioItem>)=>void; deletePortfolio:(id:string)=>void;
  addMedia:(file:MediaFile)=>void; deleteMedia:(id:string)=>void; addSubmission:(sub:Omit<SubmissionItem,'id'|'date'|'status'>)=>void; updateSubmissionStatus:(id:string,status:SubmissionItem['status'],notes?:string)=>void; deleteSubmission:(id:string)=>void; resetAllToDefault:()=>void;
}
const CMSContext=createContext<CMSContextType|undefined>(undefined);
export const CMSProvider:React.FC<{children:React.ReactNode}>=({children})=>{
  const [data,setData]=useState<CMSDataStore>(loadCMSData); const [isAuthenticated,setIsAuthenticated]=useState(false); const [authLoading,setAuthLoading]=useState(true); const [hasUnsavedChanges,setHasUnsavedChanges]=useState(false); const [isSaving,setIsSaving]=useState(false); const [lastSavedAt,setLastSavedAt]=useState<Date|null>(null);
  useEffect(()=>{applyThemeVariables(data.theme)},[data.theme]);
  const mergeServerData=(serverData:Partial<CMSDataStore>|null|undefined):CMSDataStore=>({...defaultCMSData,...(serverData||{}),submissions:serverData?.submissions??[]});
  const fetchCMS=async(authenticated:boolean)=>{const r=await fetch(authenticated?'/api/admin/cms':'/api/cms',{credentials:'same-origin'});if(!r.ok)return mergeServerData(null);const p=await r.json();return mergeServerData(p.data)};
  useEffect(()=>{let active=true;(async()=>{try{const sr=await fetch('/api/admin/session',{credentials:'same-origin'});const s=sr.ok?await sr.json():{authenticated:false};const a=Boolean(s.authenticated);if(!active)return;setIsAuthenticated(a);const server=await fetchCMS(a);if(active){setData(server);setHasUnsavedChanges(false)}}catch{if(active){setIsAuthenticated(false);setData(mergeServerData(null))}}finally{if(active)setAuthLoading(false)}})();return()=>{active=false}},[]);
  const stage=(next:CMSDataStore)=>{setData(next);saveCMSData(next);setHasUnsavedChanges(true)};
  const saveChanges=async()=>{if(!isAuthenticated)return false;setIsSaving(true);try{const r=await fetch('/api/admin/cms',{method:'PUT',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(data)});if(!r.ok)return false;setHasUnsavedChanges(false);setLastSavedAt(new Date());return true}catch{return false}finally{setIsSaving(false)}};
  const login=async(email:string,pass:string)=>{try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({email,password:pass})});if(!r.ok)return false;setIsAuthenticated(true);setData(await fetchCMS(true));setHasUnsavedChanges(false);return true}catch{return false}};
  const logout=async()=>{try{await fetch('/api/admin/logout',{method:'POST',credentials:'same-origin'})}catch{}setIsAuthenticated(false);try{setData(await fetchCMS(false))}catch{setData(mergeServerData(null))}};
  const changePassword=async(currentPassword:string,newPassword:string)=>{try{const r=await fetch('/api/admin/change-password',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({currentPassword,newPassword})});if(r.ok)setIsAuthenticated(false);return r.ok}catch{return false}};
  const updateTheme=(u:Partial<ThemeSettings>)=>stage({...data,theme:{...data.theme,...u}}); const resetThemeToDefault=()=>stage({...data,theme:defaultCMSData.theme}); const updateGlobal=(u:Partial<GlobalSettings>)=>stage({...data,global:{...data.global,...u}}); const updateNavbar=(u:Partial<NavbarSettings>)=>stage({...data,navbar:{...data.navbar,...u}}); const updateHero=(u:Partial<HeroSettings>)=>stage({...data,hero:{...data.hero,...u}}); const updateSections=(sections:SectionConfig[])=>stage({...data,sections});
  const addContentField=(item:ContentFieldItem)=>stage({...data,contentFields:[item,...data.contentFields]}); const updateContentField=(id:string,item:Partial<ContentFieldItem>)=>stage({...data,contentFields:data.contentFields.map(x=>x.id===id?{...x,...item}:x)}); const deleteContentField=(id:string)=>stage({...data,contentFields:data.contentFields.filter(x=>x.id!==id)});
  const addNews=(item:NewsItem)=>stage({...data,news:[item,...data.news]}); const updateNews=(id:string,item:Partial<NewsItem>)=>stage({...data,news:data.news.map(x=>x.id===id?{...x,...item}:x)}); const deleteNews=(id:string)=>stage({...data,news:data.news.filter(x=>x.id!==id)});
  const addBlog=(item:BlogPostItem)=>stage({...data,blog:[item,...data.blog]}); const updateBlog=(id:string,item:Partial<BlogPostItem>)=>stage({...data,blog:data.blog.map(x=>x.id===id?{...x,...item}:x)}); const deleteBlog=(id:string)=>stage({...data,blog:data.blog.filter(x=>x.id!==id)});
  const addTool=(item:ToolItem)=>stage({...data,tools:[item,...data.tools]}); const updateTool=(id:string,item:Partial<ToolItem>)=>stage({...data,tools:data.tools.map(x=>x.id===id?{...x,...item}:x)}); const deleteTool=(id:string)=>stage({...data,tools:data.tools.filter(x=>x.id!==id)});
  const addService=(item:ServiceItem)=>stage({...data,services:[item,...data.services]}); const updateService=(id:string,item:Partial<ServiceItem>)=>stage({...data,services:data.services.map(x=>x.id===id?{...x,...item}:x)}); const deleteService=(id:string)=>stage({...data,services:data.services.filter(x=>x.id!==id)});
  const addPortfolio=(item:PortfolioItem)=>stage({...data,portfolio:[item,...data.portfolio]}); const updatePortfolio=(id:string,item:Partial<PortfolioItem>)=>stage({...data,portfolio:data.portfolio.map(x=>x.id===id?{...x,...item}:x)}); const deletePortfolio=(id:string)=>stage({...data,portfolio:data.portfolio.filter(x=>x.id!==id)});
  const addMedia=(file:MediaFile)=>stage({...data,media:[file,...data.media]}); const deleteMedia=(id:string)=>stage({...data,media:data.media.filter(x=>x.id!==id)});
  const addSubmission=(sub:Omit<SubmissionItem,'id'|'date'|'status'>)=>{const temporaryId='sub-pending-'+Date.now();const pendingItem:SubmissionItem={...sub,id:temporaryId,date:new Date().toLocaleDateString('ar-SA'),status:'جديد'};setData(c=>({...c,submissions:[pendingItem,...c.submissions]}));void fetch('/api/submissions',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(sub)}).then(async r=>{if(!r.ok)throw new Error();const p=await r.json();if(p.item)setData(c=>({...c,submissions:c.submissions.map(x=>x.id===temporaryId?p.item:x)}))}).catch(()=>setData(c=>({...c,submissions:c.submissions.filter(x=>x.id!==temporaryId)})))};
  const updateSubmissionStatus=(id:string,status:SubmissionItem['status'],notes?:string)=>stage({...data,submissions:data.submissions.map(x=>x.id===id?{...x,status,adminNotes:notes||x.adminNotes}:x)}); const deleteSubmission=(id:string)=>stage({...data,submissions:data.submissions.filter(x=>x.id!==id)}); const resetAllToDefault=()=>stage(defaultCMSData);
  return <CMSContext.Provider value={{data,isAuthenticated,authLoading,hasUnsavedChanges,isSaving,lastSavedAt,login,logout,changePassword,saveChanges,updateTheme,resetThemeToDefault,updateGlobal,updateNavbar,updateHero,updateSections,addContentField,updateContentField,deleteContentField,addNews,updateNews,deleteNews,addBlog,updateBlog,deleteBlog,addTool,updateTool,deleteTool,addService,updateService,deleteService,addPortfolio,updatePortfolio,deletePortfolio,addMedia,deleteMedia,addSubmission,updateSubmissionStatus,deleteSubmission,resetAllToDefault}}>{children}</CMSContext.Provider>
};
export const useCMS=()=>{const c=useContext(CMSContext);if(!c)throw new Error('useCMS must be used within a CMSProvider');return c};
