import React, { useEffect } from 'react';
import { BrowserRouter as Router, Routes, Route, useLocation } from 'react-router-dom';
import { CMSProvider } from './context/CMSContext'; import { LanguageProvider } from './context/LanguageContext';
import { Navbar } from './components/Navbar'; import { Footer } from './components/Footer'; import { SiteSEO } from './components/SiteSEO'; import { CustomDesignRuntime } from './components/CustomDesignRuntime';
import { HomePage } from './pages/HomePage'; import { AboutPage } from './pages/AboutPage'; import { ServicesPage } from './pages/ServicesPage'; import { ServiceDetailPage } from './pages/ServiceDetailPage'; import { NewsPage } from './pages/NewsPage'; import { NewsDetailPage } from './pages/NewsDetailPage'; import { BlogPage } from './pages/BlogPage'; import { BlogDetailPage } from './pages/BlogDetailPage'; import { WorksPage } from './pages/WorksPage'; import { WorkDetailPage } from './pages/WorkDetailPage'; import { CenterHelpPage } from './pages/CenterHelpPage'; import { ResourcesPage } from './pages/ResourcesPage'; import { ToolDetailPage } from './pages/ToolDetailPage'; import { ContentFieldDetailPage } from './pages/ContentFieldDetailPage'; import { ContactPage } from './pages/ContactPage'; import { SuggestionPage } from './pages/SuggestionPage'; import { ComplaintPage } from './pages/ComplaintPage'; import { PrivacyPage } from './pages/PrivacyPage'; import { TermsPage } from './pages/TermsPage'; import { SaeedPlatformPage } from './pages/SaeedPlatformPage';
import { AdminLoginPage } from './pages/admin/AdminLoginPage'; import { AdminDashboardPage } from './pages/admin/AdminDashboardPage'; import { AdminResponsiveShell } from './components/admin/AdminResponsiveShell'; import { AdminEnhancements } from './components/admin/AdminEnhancements'; import { SaeedPlatformAdmin } from './components/admin/SaeedPlatformAdmin';
const ScrollToTop:React.FC=()=>{const{pathname}=useLocation();useEffect(()=>window.scrollTo(0,0),[pathname]);return null}; const AdminPanel=()=> <AdminResponsiveShell><AdminEnhancements><AdminDashboardPage/><SaeedPlatformAdmin/></AdminEnhancements></AdminResponsiveShell>;
const MainLayout:React.FC=()=>{const{pathname}=useLocation();const isAdminRoute=pathname.startsWith('/admin');return <div className="min-h-screen bg-[#080808] text-white font-cairo antialiased selection:bg-[#B5121B] selection:text-white flex flex-col justify-between"><SiteSEO/>{!isAdminRoute&&<><CustomDesignRuntime/><Navbar/></>}<main className="grow"><Routes><Route path="/" element={<HomePage/>}/><Route path="/about" element={<AboutPage/>}/><Route path="/content/:slug" element={<ContentFieldDetailPage/>}/><Route path="/services" element={<ServicesPage/>}/><Route path="/services/:id" element={<ServiceDetailPage/>}/><Route path="/news" element={<NewsPage/>}/><Route path="/news/:slug" element={<NewsDetailPage/>}/><Route path="/blog" element={<BlogPage/>}/><Route path="/blog/:slug" element={<BlogDetailPage/>}/><Route path="/works" element={<WorksPage/>}/><Route path="/work/:slug" element={<WorkDetailPage/>}/><Route path="/resources" element={<ResourcesPage/>}/><Route path="/resources/:sub" element={<ResourcesPage/>}/><Route path="/tools/:slug" element={<ToolDetailPage/>}/><Route path="/saeed/:id" element={<SaeedPlatformPage/>}/><Route path="/centerhelp" element={<CenterHelpPage/>}/><Route path="/contact" element={<ContactPage/>}/><Route path="/suggestion" element={<SuggestionPage/>}/><Route path="/complaint" element={<ComplaintPage/>}/><Route path="/privacy" element={<PrivacyPage/>}/><Route path="/terms" element={<TermsPage/>}/><Route path="/admin/login" element={<AdminLoginPage/>}/><Route path="/admin" element={<AdminPanel/>}/><Route path="/admin/*" element={<AdminPanel/>}/></Routes></main>{!isAdminRoute&&<Footer/>}</div>};
export function App(){return <CMSProvider><LanguageProvider><Router><ScrollToTop/><MainLayout/></Router></LanguageProvider></CMSProvider>} export default App;
